### ISSUE TITLE
How much can your code speed up SECOND?

### ISSUE THREAD

**Issue by zwqnju** [mit-han-lab/torchsparse#1]
SECOND uses [spconv](https://github.com/traveller59/spconv) to do sparse conv. How much can your code speed up SECOND? I did not find this information in your paper.

Your paper mentioned that you reimplement SECOND. Will this repo be available? If I want to reimplement SECOND using your 3d conv API, will it be easy? How can I do this?

Does this repo have similar interface like spconv.utils.VoxelGenerator in [spconv](https://github.com/traveller59/spconv) to do voxelization?

**Comment by kentangSJTU** [comment]
Hi,

Thanks for your interest in our paper. We haven't compare our implementation with latest **spconv**, which you are welcomed to have a try. However, I do remember that in our previous experiments on 3D segmentation, our implementation using **spconv** didn't reproduce results of MinkowskiNet. We therefore turn to optimize **MinkowskiEngine**.

The re-implementation of SECOND will be made available in the future and re-implementing SECOND can be easy with our interface. Please refer to [this link](https://github.com/mit-han-lab/e3d/blob/master/spvnas/core/models/semantic_kitti/minkunet.py) to checkout how to implement convolution blocks and residual blocks with `torchsparse`. Notice that the 3D part of SECOND is composed of these two types of blocks in our implementation.

This repo has similar interface like **spconv**'s VoxelGenerator, but it's more similar to MinkowskiEngine.  Examples of converting point clouds to sparse voxels can be found [here](https://github.com/mit-han-lab/e3d/tree/master/spvnas) or [here](https://github.com/mit-han-lab/e3d/blob/master/spvnas/core/datasets/semantic_kitti.py).



Best,
Haotian

**Comment by zwqnju** [comment]
Thanks a lot! Very useful!

**Comment by 619862306** [comment]
I want to reimplement SECOND with torchsparse , how can I do this?
