### ISSUE TITLE
Sparsity brings no speed up

### ISSUE THREAD

**Issue by NoOneUST** [mit-han-lab/torchsparse#100]
I generate a mask to replace 50% non-zero elements 0. Here `feat.shape=[N,C], view_std_mask.shape=[N]`
```
feat[view_std_mask] = 0
```
then I send it to a sparse convolution:
```
# ----sparse conv 3d backbone----
with record_function(f"neucon_net_stage{i}_sparse_conv_3d_backbone"):
    torch.cuda.synchronize()
    start_time = time.time()
    point_feat = PointTensor(feat, r_coords)
    feat = self.sp_convs[i](point_feat)
    torch.cuda.synchronize()
    iter_time_sparse_3d[f'stage{i}'].append(time.time() - start_time)
```
But I observe no speed up (performance is comparable). The original time is `3d_stage0: 0.04869642266471961, stage 1: 0.05006156846674906, stage2: 0.061345104577903924`, after sparsifying, the time is `3d_stage0: 0.05488752330864332, stage 1: 0.05297503954803889, stage2: 0.05243182428334936`. Here the stage0 has smaller HWD but more channels, while stage2 has larger HWD but fewer channels.

**Comment by zhijian-liu** [comment]
This is the expected behavior. We will not skip the computation for zero features. You should only send in these points with non-zero features to skip the computation for zero features.

**Comment by NoOneUST** [comment]
> This is the expected behavior. We will not skip the computation for zero features. You should only send in these points with non-zero features to skip the computation for zero features.

Now I understand. Thank you so much for your quick reply.
