### ISSUE TITLE
Why not constraining the max coordinates during downsampling?

### ISSUE THREAD

**Issue by caiqi** [mit-han-lab/torchsparse#101]
Thanks for the awesome repo! I found that with stride=2, the outputs coordinates may be larger than the input range. And I found that there is a comment here https://github.com/mit-han-lab/torchsparse/blob/master/torchsparse/nn/functional/downsample.py#L40. I just wonder why not adding the coordinates max constrain since it seems very straightforward?

**Comment by zhijian-liu** [comment]
It's indeed very easy to support this. However, our internal detection codebase is sensitive to this constraint. We will fix this once we have figured this out. At the same time, you may clone our repo, add this constraint, and compile it (with `pip install .`) if this causes an issue in your application. Sorry for the inconvenience.
