### ISSUE TITLE
AttributeError: module 'torchsparse_cuda' has no attribute 'hash_forward'

### ISSUE THREAD

**Issue by Burningdust21** [mit-han-lab/torchsparse#102]
Hi,

I've been working on a project that needs  torchsparse v1.1.0, but ran into following error:

```
Traceback (most recent call last):
................
  File "/miniconda3/envs/NR+/lib/python3.7/site-packages/torchsparse/nn/functional/hash.py", line 44, in sphash
    return hash_gpu(idx)
  File "/miniconda3/envs/NR+/lib/python3.7/site-packages/torchsparse/nn/functional/hash.py", line 12, in forward
    return torchsparse_cuda.hash_forward(idx.contiguous())
AttributeError: module 'torchsparse_cuda' has no attribute 'hash_forward'
```

Cuda version is 10.1, I've already tried reinstall pytorch, sparse hash and torchsparse, but didn't solve anything. Any idea why this happened? 

Thanks.

**Comment by CCInc** [comment]
Hi, If you could uninstall torchsparse and reinstall with `pip install -v git+https://github.com/mit-han-lab/torchsparse.git`, then upload the output of that to gist.github.com, that will be very helpful!

**Comment by Burningdust21** [comment]
Here is the out put of installation: https://gist.github.com/Burningdust21/60e87ffccbbc42db4c7f7f4377fef6ad

**Comment by zhijian-liu** [comment]
Thanks for sending the log. I'm wondering if you could try to add `FORCE_CUDA=1` before the `pip install` command.

**Comment by Burningdust21** [comment]
Thanks for you replay! It turns out my compile environment doesn't has a valid CUDA configuration. Everything works fine now.
