### ISSUE TITLE
Some questions about the voxelization and convolution ops

### ISSUE THREAD

**Issue by PhoenVujih** [mit-han-lab/torchsparse#106]
Hi, @zhijian-liu , I am considering using torchsparse to build my own model. Here I have some questions about the voxelization and convolution operations.  

I notice that the `sparse_quantize` can be used to remove the duplicates. What does it mean by removing the duplicates? Duplicated points in the voxel and only one point for a single voxel? 

The second question is about the dimensions of the input and output of the voxelization and convolution operations. Do the output tensors of the mentioned operations have fixed size once the input is given? This question is mainly about the deployment of the model since TensorRT requires fixed dimensions of inputs and outputs. 

By the way, have you considered the deployment of the models? It would be great if the feature of the deployment can be added into the project.

**Comment by CCInc** [comment]
As for the first point, you're correct that `sparse_quantize` removes duplicates, where duplicates means multiple points contained in the same voxel. `sparse_quantize` voxelizes the point cloud based on the grid and selects one point from each voxel using `np.unique`.

**Comment by CCInc** [comment]
You may be interested in this thread regarding model deployment. https://github.com/mit-han-lab/torchsparse/issues/71#issuecomment-897639382
