### ISSUE TITLE
question abount torchsparse inference time

### ISSUE THREAD

**Issue by owphoo** [mit-han-lab/torchsparse#108]
I use only one coord and one feature as sparse tensor, and use a 3d unet network. It costs about 20ms. When I use abount 1000 coords and features, the  inference time is abount 10 + ms. Does it Meet expectations?

**Comment by kentangSJTU** [comment]
Hello @owphoo,

I feel it's in a reasonable range. Note that for such small inputs, data movement & kernel map construction instead of actual MatMul may dominate the runtime. In general I think experimenting on a larger input might give more meaningful results.

Best,
Haotian

**Comment by owphoo** [comment]
@kentangSJTU thanks.
