### ISSUE TITLE
[BUG] The actual dilation is always 1 in torchsparse.nn.functional.conv3d

### ISSUE THREAD

**Issue by snuffle-PX** [mit-han-lab/torchsparse#109]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://github.com/mit-han-lab/torchsparse/blob/6c305305e2dd6b2ce3274c19ec3cc7259ca45ce1/torchsparse/nn/functional/conv.py#L113-L115

### Expected Behavior

`offsets = get_kernel_offsets(kernel_size, stride=input.stride, dilation=dilation, device=feats.device)`

### Environment

```markdown
- GCC:7.5.0
- NVCC:11.1
- PyTorch:1.9.0
- PyTorch CUDA:11.1
- TorchSparse:1.4.0
```

**Comment by zhijian-liu** [comment]
Thanks for reporting this issue! Could you please submit a PR to fix this issue?
