### ISSUE TITLE
[BUG] AttributeError: 'SparseTensor' object has no attribute 'check'

### ISSUE THREAD

**Issue by ZERO2ER0** [mit-han-lab/torchsparse#111]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
import torch
from torchsparse import PointTensor, SparseTensor
import torchsparse.nn.functional as spf

def initial_voxelize(z, init_res, after_res):
    new_float_coord = torch.cat(
        [(z.C[:, :3] * init_res) / after_res, z.C[:, -1].view(-1, 1)], 1)

    pc_hash = spf.sphash(torch.floor(new_float_coord).int())
    sparse_hash = torch.unique(pc_hash)
    idx_query = spf.sphashquery(pc_hash, sparse_hash)
    counts = spf.spcount(idx_query.int(), len(sparse_hash))

    inserted_coords = spf.spvoxelize(torch.floor(new_float_coord), idx_query,
                                   counts)
    inserted_coords = torch.round(inserted_coords).int()
    inserted_feat = spf.spvoxelize(z.F, idx_query, counts)

    print(inserted_coords)

    new_tensor = SparseTensor(inserted_feat, inserted_coords, 1)
    new_tensor.check()
    z.additional_features['idx_query'][1] = idx_query
    z.additional_features['counts'][1] = counts
    z.C = new_float_coord

    return new_tensor


num_points = 5
init_res = 1.0
after_res = 0.01

# create dummy pointcould
pc = torch.rand(num_points, 3)
# add _batch_dimension
pc = torch.cat([pc, torch.zeros(pc.shape[0], 1)], dim=-1)

pc = PointTensor(pc[:,:3], pc)

ret = initial_voxelize(pc, init_res, after_res) 
```

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_51548/755603267.py in <module>
     39 pc = PointTensor(pc[:,:3], pc)
     40 
---> 41 ret = initial_voxelize(pc, init_res, after_res)

/tmp/ipykernel_51548/755603267.py in initial_voxelize(z, init_res, after_res)
     20 
     21     new_tensor = SparseTensor(inserted_feat, inserted_coords, 1)
---> 22     new_tensor.check()
     23     z.additional_features['idx_query'][1] = idx_query
     24     z.additional_features['counts'][1] = counts

### Expected Behavior

How can i solve this problem on a platform with 4xGPU3090? Thank you very much! @zhijian-liu 
### Environment

```markdown
- GCC: 7.5.0
- NVCC: 11.1, V11.1.74
- PyTorch: 1.9.0
- PyTorch CUDA: 11.1
- TorchSparse: 1.4.0
```

**Comment by zhijian-liu** [comment]
Could you please try to replace `new_tensor.check()` with `new_tensor.cmaps.setdefault(new_tensor.stride, new_tensor.coords)` (refer to https://github.com/mit-han-lab/spvnas/blob/master/core/models/utils.py#L26 for more details)?

**Comment by ZERO2ER0** [comment]
> Could you please try to replace `new_tensor.check()` with
> 
> ```
> new_tensor.cmaps.setdefault(new_tensor.stride, new_tensor.coords)
> ```
> 
> (refer to https://github.com/mit-han-lab/spvnas/blob/master/core/models/utils.py#L26 for more details)?

It worked! Think you very much!

**Comment by ZilingLiu** [comment]
In latest version，AttributeError: 'SparseTensor' object has no attribute 'cmaps'. Is there any change?

**Comment by ravishankark1992** [comment]
Hi, I'm facing the same issue, Could you please share an update if there's a solution available? 
TIA

**Comment by c-torre** [comment]
For reference, the is something in these lines:

```python
# new_tensor.cmaps.setdefault(new_tensor.stride, new_tensor.coords)
new_tensor._caches.cmaps.setdefault(new_tensor.stride, new_tensor.coords)

# new_tensor.cmaps = x.cmaps
new_tensor._caches.cmaps = x._caches.cmaps
new_tensor._caches.kmaps = x._caches.kmaps
```

#229
