### ISSUE TITLE
Is there a way to convert a model using torchsparse into torchscript for production in C++?

### ISSUE THREAD

**Issue by runorz** [mit-han-lab/torchsparse#113]
I have used spvcnn model and it has used Torchsparse, but found it hard to convert to TorchScript. Is there any instruction in covering torchsparse model into production?

**Comment by zhijian-liu** [comment]
This would be much more complicated than that. We haven't tried this but you may refer to https://pytorch.org/tutorials/advanced/torch_script_custom_ops.html for more details.
