### ISSUE TITLE
Compatibility between torchsparse and pytorch autograd engines

### ISSUE THREAD

**Issue by aymenmir1** [mit-han-lab/torchsparse#123]
I am wondering whether torchsparse's autograd engine is compatible with pytorch's autograd engine?Is it possible to integrate a neural network built using torch sparse with another network built using normal pytorch. For example
```
import torch.nn as nn
from torchsparse import nn as spnn

model1 = snn.sequential( ... )

model2 = nn.sequential( ... )

out =  model2(model1(inputs))

loss = nn.MSEloss(out, gt)

loss.backward()

```

**Comment by zhijian-liu** [comment]
Yes, they are compatible. [This](https://github.com/mit-han-lab/spvnas/blob/master/core/models/semantic_kitti/minkunet.py#L178) could be a good example where all modules expect the classifier are TorchSparse modules while the final classifier is a standard PyTorch linear layer.
