### ISSUE TITLE
About Multiplication

### ISSUE THREAD

**Issue by suyunzzz** [mit-han-lab/torchsparse#128]
@zhijian-liu 
hello, if i use torchsprse how can i build a SE-module(it will use a function to multiply two tensor, just[ like ](https://github.com/NVIDIA/MinkowskiEngine/blob/b683e25a2482f49ea851dc4c629ffffdf70e0e37/MinkowskiEngine/modules/senet_block.py#L42) this

`        self.broadcast_mul = ME.MinkowskiBroadcastMultiplication()`

**Comment by zhijian-liu** [comment]
Given two input sparse tensors `a` and `b` with the same coordinates (`a.C == b.C`), the element-wise multiplication can be implemented as follows:
```
c = SparseTensor(a.F * b.F, a.C)
```

**Comment by suyunzzz** [comment]
> Given two input sparse tensors `a` and `b` with the same coordinates and stride (i.e., `a.C == b.C` and `a.s == b.s`), the element-wise multiplication can be implemented as follows:
> 
> ```
> c = SparseTensor(a.F * b.F, a.C, a.s)
> ```
thanks a lot: )

**Comment by suyunzzz** [comment]
hello, zhijian, i want to know how can i achieve a Self-Attenion Modules by torch-sparse or MinkowskiEngine, it seems that is not a  ops to achieve it?
just like this:
```
        # Self-Attention
        # batch = [N1*C, N2*C]
        # [N1*C, N2*C] ===> [N1*N1, N2*N2] ===> softmax ===>socre: [N1*N1, N2*N2] ===> [N1*C, N2*C]*[N1*N1, N2*N2] ===> [N1*C, N2*C]
```

i have a idea, the most difficult point is that sparseTensor in one batch may have different coordinates number after downsample, so could i use some sample function(i.e. FPS or RS) to select same number points, and then use point-wise Self-Attention to get long range context?

but i run the multiplication function, it just can element-wise multiplication, could you tell me what should i do?
i am looking forward to your reply, thanks a lot : )

**Comment by suyunzzz** [comment]
@zhijian-liu : )

**Comment by zhijian-liu** [comment]
It's a bit hard to parallelize over the batch dimension as different point clouds within the batch might have different number of points. However, it should be fairly easy to implement if you process each instance within the batch sequentially. A rough implementation could be something like this:
```
batch_size = torch.max(x.coords[:, -1]).item() + 1
feats = torch.zeros_like(x.feats)
for k in range(batch_size):
    indices = (x.coords[:, -1] == k)
    scores = torch.matmul(x.feats[indices], x.feats[indices].t())
    scores = torch.softmax(scores, dim=-1)
    feats[indices] = torch.matmul(scores, x.feats[indices])
y = SparseTensor(feats, x.coords)
```
