### ISSUE TITLE
ModuleNotFoundError: No module named 'torchsparse.point_tensor'

### ISSUE THREAD

**Issue by zwy1996** [mit-han-lab/torchsparse#129]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you followed all the steps in the FAQ?

- [X] I have tried the steps in the FAQ.

### Current Behavior

Hi,

When I used the instruction to install the lib, but when I ran experiments I met the error, Could you please give me some advice？

torchsparse==1.4.0

best wishes to you!

### Error Line

--

### Environment

```markdown
- GCC:
- NVCC:
- PyTorch:
- PyTorch CUDA:
```

### Full Error Log

<details>
  <summary>Error Log</summary>

  [PUT YOUR ERROR LOG HERE]
</details>

**Comment by zhijian-liu** [comment]
This is due to the API changes from v1.4.0. You could change the import to `from torchsparse import PointTensor`.

**Comment by zwy1996** [comment]
ok, Thank you very much!

I have solved this problem
