### ISSUE TITLE
[BUG] Integer division error in sparse Conv3d forward

### ISSUE THREAD

**Issue by Teaksters** [mit-han-lab/torchsparse#131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

First of all thanks for the useful library!

I am currently getting an integer division error when forwarding a torchsparse.nn.Conv3d layer: 

```RuntimeError: Integer division of tensors using div or / is no longer supported, and in a future release div will perform true division as in Python 3. Use true_divide or floor_divide (// in Python) instead.```

It originates from: ```torchsparse/nn/functional/downsample.py", line 28, in spdownsample```

Looking through the existing issues I found this one that looks a lot like my current error #125. It seems that the proposed fix has caused the issue, I am not familiar with contributing to GitHub projects but am open to applying changes if necessary.

Let me know!

### Environment

```markdown
- GCC: (Debian 8.3.0-6) 8.3.0
- NVCC: release 11.3, V11.3.109
- PyTorch: 1.6.0
- PyTorch CUDA: 10.2
- TorchSparse: 1.4.0
```

**Comment by CCInc** [comment]
Hi @Teaksters thanks for the report! I see you're using pytorch 1.6.0, would you be able to update your pytorch version and see if it still occurs? I think version 1.8 or 1.9 may work. Let me know if not.
