### ISSUE TITLE
to dense ,dear autor ,it there any api for to the dense tensor?

### ISSUE THREAD

**Issue by emilypython** [mit-han-lab/torchsparse#132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

to dense ,dear autor ,it there any api for to the dense tensor?

### Expected Behavior

to dense ,dear autor ,it there any api for to the dense tensor?

### Environment

```markdown
gcc 7.50
```

### Anything else?

to dense ,dear autor ,it there any api for to the dense tensor?

If there,could I get an  example ahout using to_dense function?

**Comment by zhijian-liu** [comment]
See https://github.com/mit-han-lab/torchsparse/issues/88.
