### ISSUE TITLE
build faild

### ISSUE THREAD

**Issue by StarsTesla** [mit-han-lab/torchsparse#136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you followed all the steps in the FAQ?

- [X] I have tried the steps in the FAQ.

### Current Behavior

I clone the repo and try to pip install . but what ever I have done, it always shows the error.

I have tried:
downgrade the cuda to 10.2
downgrade the pytorch 
recreate a new conda env

### Error Line

    LINK : fatal error LNK1181: cannot open input file 'C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7\Release\torchsparse\backend\pybind_cuda.obj'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\link.exe' failed with exit status 1181
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\ProgramData\Anaconda3\envs\temp\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Stars\\AppData\\Local\\Temp\\pip-req-build-yc1iu00q\\setup.py'"'"'; __file__='"'"'C:\\Users\\Stars\\AppData\\Local\\Temp\\pip-req-build-yc1iu00q\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Stars\AppData\Local\Temp\pip-record-3dwx5o95\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\ProgramData\Anaconda3\envs\temp\Include\torchsparse' Check the logs for full command output.

### Environment

```markdown
- GCC:8.1.0
- NVCC:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Mar_21_19:24:09_Pacific_Daylight_Time_2021
Cuda compilation tools, release 11.3, V11.3.58
Build cuda_11.3.r11.3/compiler.29745058_0

- PyTorch:
pytorch                   1.10.1          py3.7_cuda11.3_cudnn8_0    pytorch

- Python 3.7.7
- Gpu：3080ti
- cpu：i7
- os：win10
- VS：2019
```

### Full Error Log

  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
Building wheels for collected packages: torchsparse
  Building wheel for torchsparse (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\ProgramData\Anaconda3\envs\temp\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Stars\\AppData\\Local\\Temp\\pip-req-build-yc1iu00q\\setup.py'"'"'; __file__='"'"'C:\\Users\\Stars\\AppData\\Local\\Temp\\pip-req-build-yc1iu00q\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Stars\AppData\Local\Temp\pip-wheel-v85937gi'
       cwd: C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\
  Complete output (60 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\torchsparse
  copying torchsparse\operators.py -> build\lib.win-amd64-3.7\torchsparse
  copying torchsparse\tensor.py -> build\lib.win-amd64-3.7\torchsparse
  copying torchsparse\version.py -> build\lib.win-amd64-3.7\torchsparse
  copying torchsparse\__init__.py -> build\lib.win-amd64-3.7\torchsparse
  creating build\lib.win-amd64-3.7\torchsparse\nn
  copying torchsparse\nn\__init__.py -> build\lib.win-amd64-3.7\torchsparse\nn
  creating build\lib.win-amd64-3.7\torchsparse\utils
  copying torchsparse\utils\collate.py -> build\lib.win-amd64-3.7\torchsparse\utils
  copying torchsparse\utils\quantize.py -> build\lib.win-amd64-3.7\torchsparse\utils
  copying torchsparse\utils\utils.py -> build\lib.win-amd64-3.7\torchsparse\utils
  copying torchsparse\utils\__init__.py -> build\lib.win-amd64-3.7\torchsparse\utils
  creating build\lib.win-amd64-3.7\torchsparse\nn\functional
  copying torchsparse\nn\functional\activation.py -> build\lib.win-amd64-3.7\torchsparse\nn\functional
  copying torchsparse\nn\functional\conv.py -> build\lib.win-amd64-3.7\torchsparse\nn\functional
  copying torchsparse\nn\functional\count.py -> build\lib.win-amd64-3.7\torchsparse\nn\functional
  copying torchsparse\nn\functional\crop.py -> build\lib.win-amd64-3.7\torchsparse\nn\functional
  copying torchsparse\nn\functional\devoxelize.py -> build\lib.win-amd64-3.7\torchsparse\nn\functional
  copying torchsparse\nn\functional\downsample.py -> build\lib.win-amd64-3.7\torchsparse\nn\functional
  copying torchsparse\nn\functional\hash.py -> build\lib.win-amd64-3.7\torchsparse\nn\functional
  copying torchsparse\nn\functional\pooling.py -> build\lib.win-amd64-3.7\torchsparse\nn\functional
  copying torchsparse\nn\functional\query.py -> build\lib.win-amd64-3.7\torchsparse\nn\functional
  copying torchsparse\nn\functional\voxelize.py -> build\lib.win-amd64-3.7\torchsparse\nn\functional
  copying torchsparse\nn\functional\__init__.py -> build\lib.win-amd64-3.7\torchsparse\nn\functional
  creating build\lib.win-amd64-3.7\torchsparse\nn\modules
  copying torchsparse\nn\modules\activation.py -> build\lib.win-amd64-3.7\torchsparse\nn\modules
  copying torchsparse\nn\modules\bev.py -> build\lib.win-amd64-3.7\torchsparse\nn\modules
  copying torchsparse\nn\modules\conv.py -> build\lib.win-amd64-3.7\torchsparse\nn\modules
  copying torchsparse\nn\modules\crop.py -> build\lib.win-amd64-3.7\torchsparse\nn\modules
  copying torchsparse\nn\modules\norm.py -> build\lib.win-amd64-3.7\torchsparse\nn\modules
  copying torchsparse\nn\modules\pooling.py -> build\lib.win-amd64-3.7\torchsparse\nn\modules
  copying torchsparse\nn\modules\__init__.py -> build\lib.win-amd64-3.7\torchsparse\nn\modules
  creating build\lib.win-amd64-3.7\torchsparse\nn\utils
  copying torchsparse\nn\utils\apply.py -> build\lib.win-amd64-3.7\torchsparse\nn\utils
  copying torchsparse\nn\utils\kernel.py -> build\lib.win-amd64-3.7\torchsparse\nn\utils
  copying torchsparse\nn\utils\__init__.py -> build\lib.win-amd64-3.7\torchsparse\nn\utils
  running build_ext
  building 'torchsparse.backend' extension
  creating C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7
  creating C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7\Release
  creating C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7\Release\torchsparse
  creating C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7\Release\torchsparse\backend
  creating C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7\Release\torchsparse\backend\convolution
  creating C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7\Release\torchsparse\backend\devoxelize
  creating C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7\Release\torchsparse\backend\hash
  creating C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7\Release\torchsparse\backend\hashmap
  creating C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7\Release\torchsparse\backend\others
  creating C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7\Release\torchsparse\backend\voxelize
  Emitting ninja build file C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7\Release\build.ninja...
  Compiling objects...
  Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
  1.10.2
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\ProgramData\Anaconda3\envs\temp\lib\site-packages\torch\lib "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\lib/x64" /LIBPATH:C:\ProgramData\Anaconda3\envs\temp\libs /LIBPATH:C:\ProgramData\Anaconda3\envs\temp\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x64" c10.lib torch.lib torch_cpu.lib torch_python.lib cudart.lib c10_cuda.lib torch_cuda_cu.lib torch_cuda_cpp.lib /EXPORT:PyInit_backend C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7\Release\torchsparse\backend\pybind_cuda.obj C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7\Release\torchsparse\backend\convolution\convolution_cpu.obj C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7\Release\torchsparse\backend\convolution\convolution_cuda.obj C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7\Release\torchsparse\backend\devoxelize\devoxelize_cpu.obj C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7\Release\torchsparse\backend\devoxelize\devoxelize_cuda.obj C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7\Release\torchsparse\backend\hash\hash_cpu.obj C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7\Release\torchsparse\backend\hash\hash_cuda.obj C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7\Release\torchsparse\backend\hashmap\hashmap_cpu.obj C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7\Release\torchsparse\backend\hashmap\hashmap_cuda.obj C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7\Release\torchsparse\backend\others\count_cpu.obj C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7\Release\torchsparse\backend\others\count_cuda.obj C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7\Release\torchsparse\backend\others\query_cpu.obj C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7\Release\torchsparse\backend\others\query_cuda.obj C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7\Release\torchsparse\backend\voxelize\voxelize_cpu.obj C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7\Release\torchsparse\backend\voxelize\voxelize_cuda.obj /OUT:build\lib.win-amd64-3.7\torchsparse\backend.cp37-win_amd64.pyd /IMPLIB:C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7\Release\torchsparse\backend\backend.cp37-win_amd64.lib
  LINK : fatal error LNK1181: cannot open input file 'C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7\Release\torchsparse\backend\pybind_cuda.obj'
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\link.exe' failed with exit status 1181
  ----------------------------------------
  ERROR: Failed building wheel for torchsparse
  Running setup.py clean for torchsparse
Failed to build torchsparse
Installing collected packages: torchsparse
    Running setup.py install for torchsparse ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\ProgramData\Anaconda3\envs\temp\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Stars\\AppData\\Local\\Temp\\pip-req-build-yc1iu00q\\setup.py'"'"'; __file__='"'"'C:\\Users\\Stars\\AppData\\Local\\Temp\\pip-req-build-yc1iu00q\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Stars\AppData\Local\Temp\pip-record-3dwx5o95\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\ProgramData\Anaconda3\envs\temp\Include\torchsparse'
         cwd: C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\
    Complete output (60 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\torchsparse
    copying torchsparse\operators.py -> build\lib.win-amd64-3.7\torchsparse
    copying torchsparse\tensor.py -> build\lib.win-amd64-3.7\torchsparse
    copying torchsparse\version.py -> build\lib.win-amd64-3.7\torchsparse
    copying torchsparse\__init__.py -> build\lib.win-amd64-3.7\torchsparse
    creating build\lib.win-amd64-3.7\torchsparse\nn
    copying torchsparse\nn\__init__.py -> build\lib.win-amd64-3.7\torchsparse\nn
    creating build\lib.win-amd64-3.7\torchsparse\utils
    copying torchsparse\utils\collate.py -> build\lib.win-amd64-3.7\torchsparse\utils
    copying torchsparse\utils\quantize.py -> build\lib.win-amd64-3.7\torchsparse\utils
    copying torchsparse\utils\utils.py -> build\lib.win-amd64-3.7\torchsparse\utils
    copying torchsparse\utils\__init__.py -> build\lib.win-amd64-3.7\torchsparse\utils
    creating build\lib.win-amd64-3.7\torchsparse\nn\functional
    copying torchsparse\nn\functional\activation.py -> build\lib.win-amd64-3.7\torchsparse\nn\functional
    copying torchsparse\nn\functional\conv.py -> build\lib.win-amd64-3.7\torchsparse\nn\functional
    copying torchsparse\nn\functional\count.py -> build\lib.win-amd64-3.7\torchsparse\nn\functional
    copying torchsparse\nn\functional\crop.py -> build\lib.win-amd64-3.7\torchsparse\nn\functional
    copying torchsparse\nn\functional\devoxelize.py -> build\lib.win-amd64-3.7\torchsparse\nn\functional
    copying torchsparse\nn\functional\downsample.py -> build\lib.win-amd64-3.7\torchsparse\nn\functional
    copying torchsparse\nn\functional\hash.py -> build\lib.win-amd64-3.7\torchsparse\nn\functional
    copying torchsparse\nn\functional\pooling.py -> build\lib.win-amd64-3.7\torchsparse\nn\functional
    copying torchsparse\nn\functional\query.py -> build\lib.win-amd64-3.7\torchsparse\nn\functional
    copying torchsparse\nn\functional\voxelize.py -> build\lib.win-amd64-3.7\torchsparse\nn\functional
    copying torchsparse\nn\functional\__init__.py -> build\lib.win-amd64-3.7\torchsparse\nn\functional
    creating build\lib.win-amd64-3.7\torchsparse\nn\modules
    copying torchsparse\nn\modules\activation.py -> build\lib.win-amd64-3.7\torchsparse\nn\modules
    copying torchsparse\nn\modules\bev.py -> build\lib.win-amd64-3.7\torchsparse\nn\modules
    copying torchsparse\nn\modules\conv.py -> build\lib.win-amd64-3.7\torchsparse\nn\modules
    copying torchsparse\nn\modules\crop.py -> build\lib.win-amd64-3.7\torchsparse\nn\modules
    copying torchsparse\nn\modules\norm.py -> build\lib.win-amd64-3.7\torchsparse\nn\modules
    copying torchsparse\nn\modules\pooling.py -> build\lib.win-amd64-3.7\torchsparse\nn\modules
    copying torchsparse\nn\modules\__init__.py -> build\lib.win-amd64-3.7\torchsparse\nn\modules
    creating build\lib.win-amd64-3.7\torchsparse\nn\utils
    copying torchsparse\nn\utils\apply.py -> build\lib.win-amd64-3.7\torchsparse\nn\utils
    copying torchsparse\nn\utils\kernel.py -> build\lib.win-amd64-3.7\torchsparse\nn\utils
    copying torchsparse\nn\utils\__init__.py -> build\lib.win-amd64-3.7\torchsparse\nn\utils
    running build_ext
    building 'torchsparse.backend' extension
    creating C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7
    creating C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7\Release
    creating C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7\Release\torchsparse
    creating C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7\Release\torchsparse\backend
    creating C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7\Release\torchsparse\backend\convolution
    creating C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7\Release\torchsparse\backend\devoxelize
    creating C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7\Release\torchsparse\backend\hash
    creating C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7\Release\torchsparse\backend\hashmap
    creating C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7\Release\torchsparse\backend\others
    creating C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7\Release\torchsparse\backend\voxelize
    Emitting ninja build file C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7\Release\build.ninja...
    Compiling objects...
    Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
    1.10.2
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\ProgramData\Anaconda3\envs\temp\lib\site-packages\torch\lib "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\lib/x64" /LIBPATH:C:\ProgramData\Anaconda3\envs\temp\libs /LIBPATH:C:\ProgramData\Anaconda3\envs\temp\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x64" c10.lib torch.lib torch_cpu.lib torch_python.lib cudart.lib c10_cuda.lib torch_cuda_cu.lib torch_cuda_cpp.lib /EXPORT:PyInit_backend C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7\Release\torchsparse\backend\pybind_cuda.obj C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7\Release\torchsparse\backend\convolution\convolution_cpu.obj C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7\Release\torchsparse\backend\convolution\convolution_cuda.obj C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7\Release\torchsparse\backend\devoxelize\devoxelize_cpu.obj C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7\Release\torchsparse\backend\devoxelize\devoxelize_cuda.obj C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7\Release\torchsparse\backend\hash\hash_cpu.obj C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7\Release\torchsparse\backend\hash\hash_cuda.obj C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7\Release\torchsparse\backend\hashmap\hashmap_cpu.obj C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7\Release\torchsparse\backend\hashmap\hashmap_cuda.obj C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7\Release\torchsparse\backend\others\count_cpu.obj C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7\Release\torchsparse\backend\others\count_cuda.obj C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7\Release\torchsparse\backend\others\query_cpu.obj C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7\Release\torchsparse\backend\others\query_cuda.obj C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7\Release\torchsparse\backend\voxelize\voxelize_cpu.obj C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7\Release\torchsparse\backend\voxelize\voxelize_cuda.obj /OUT:build\lib.win-amd64-3.7\torchsparse\backend.cp37-win_amd64.pyd /IMPLIB:C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7\Release\torchsparse\backend\backend.cp37-win_amd64.lib
    LINK : fatal error LNK1181: cannot open input file 'C:\Users\Stars\AppData\Local\Temp\pip-req-build-yc1iu00q\build\temp.win-amd64-3.7\Release\torchsparse\backend\pybind_cuda.obj'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\link.exe' failed with exit status 1181
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\ProgramData\Anaconda3\envs\temp\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Stars\\AppData\\Local\\Temp\\pip-req-build-yc1iu00q\\setup.py'"'"'; __file__='"'"'C:\\Users\\Stars\\AppData\\Local\\Temp\\pip-req-build-yc1iu00q\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Stars\AppData\Local\Temp\pip-record-3dwx5o95\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\ProgramData\Anaconda3\envs\temp\Include\torchsparse' Check the logs for full command output._

**Comment by StarsTesla** [comment]
At first it shows the [ninja -v] problem, after I change the -v to --version, then the problem shows above, and keep same no matter what I have done.

**Comment by zhijian-liu** [comment]
Thanks for reporting this issue! Unfortunately, we haven't tested the installation on Windows and don't currently have the environment to reproduce the error.

**Comment by carlosedubarreto** [comment]
Hello @StarsTesla I was able to built and install.
I did some explanation on this issue
https://github.com/mit-han-lab/torchsparse/issues/12#issuecomment-1286733835

Hope it helps.
