### ISSUE TITLE
about voxel's neighbor

### ISSUE THREAD

**Issue by suyunzzz** [mit-han-lab/torchsparse#137]
hello, Zhijian

I want to know how can i get the neighbor voxels of a central voxel?
In the picture, we can make some offset with central pixel(i.e. (-1, -1), (-1, 0), (-1, 1)...), can we do this in the voxel?

**Comment by zhijian-liu** [comment]
You may refer to `torchsparse.functional.sphash` (at https://github.com/mit-han-lab/torchsparse/blob/master/torchsparse/nn/functional/hash.py#L10).
