### ISSUE TITLE
Can support cuda11?

### ISSUE THREAD

**Issue by yangzuyuanhao** [mit-han-lab/torchsparse#138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am using RTX 3060. which must requires CUDA>11.1

Inside Conda, the torchsparse can compile successfully, but will raise err in runtime:
"AttributeError: module 'torchsparse.backend' has no attribute 'hash_cuda'.

It looks like the torchsparse didn't compatible with cuda 11? (conda environment)

### Environment

```markdown
- GCC:9.3
- NVCC: 
- PyTorch: 1.10
- PyTorch CUDA: 11
- TorchSparse: 1.4
```

**Comment by CCInc** [comment]
Hello. It is compatible. Please try going through the FAQ and update us with the information requested there. https://github.com/mit-han-lab/torchsparse/blob/master/docs/FAQ.md
