### ISSUE TITLE
Is the torchsparse.nn.Conv3d equivalent to the sparse 3D Conv or the submanifold sparse 3D Conv?

### ISSUE THREAD

**Issue by jialeli1** [mit-han-lab/torchsparse#14]
Hi, is the torchsparse.nn.Conv3d equivalent to the sparse 3D Conv or the submanifold sparse 3D Conv?

**Comment by kentangSJTU** [comment]
Hi,

It depends on the stride. Stride=1 version is the submanifold convolution and stride=2 version should be the sparse convolution version.

Best,
Haotian

**Comment by zhijian-liu** [comment]
I'm closing this issue due to the inactivity. Please feel free to reopen it if the problem has not been resolved.
