### ISSUE TITLE
How to install TorchSparse in docker?

### ISSUE THREAD

**Issue by mengshiyu0109** [mit-han-lab/torchsparse#140]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you followed all the steps in the FAQ?

- [X] I have tried the steps in the FAQ.

### Current Behavior

I just use "apt-get install libsparsehash-dev" in the docker.

BELOW:
root@ea155398311a:/workspace# apt-get install libsparsehash-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libsparsehash-dev is already the newest version (2.0.3-1).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
However ,

when I run the python file.
It told not torchparse.

### Error Line

oot@ea155398311a:/workspace# apt-get install libsparsehash-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libsparsehash-dev is already the newest version (2.0.3-1).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.

### Environment

```markdown
- GCC:9
- NVCC:
- PyTorch:1.8.1
- PyTorch CUDA: 11.1
```

### Full Error Log

<details>
  <summary>Error Log</summary>

  [PUT YOUR ERROR LOG HERE]
</details>

**Comment by zhijian-liu** [comment]
`libsparsehash-dev` is just one dependency required for TorchSparse. You may follow the instruction at https://github.com/mit-han-lab/torchsparse#installation to install TorchSparse.

**Comment by mengshiyu0109** [comment]
> `libsparsehash-dev` is just one dependency required for TorchSparse. You may follow the instruction at https://github.com/mit-han-lab/torchsparse#installation to install TorchSparse.

thanks for reply!!!

could I get an dockerfile in ubuntu20.04 python3.8?
when I run"pip install..."
 I always got an error

**Comment by zhijian-liu** [comment]
Could you post the full error message?

**Comment by mengshiyu0109** [comment]
> Could you post the full error message?

aha I have solved the error,
 
sorry to disturb you !
