### ISSUE TITLE
Is Point Cloud Regression possible with MSE Loss?

### ISSUE THREAD

**Issue by davodogster** [mit-han-lab/torchsparse#143]
Hi, awesome work on the repo! @zhijian-liu 
Data input: Sparse individual point clouds. All different number of points. Each has a single associated regression value. so data = coords = x,y,z coordinates, **feats = None** (because it's just a point cloud and every point has no features, not even intensity), 'targets': single value per point cloud/example.
Desired output - estimate of that value using MSE loss.

Is this network possible using Torchsparse?
Best Regards, Sam

**Comment by zhijian-liu** [comment]
In this case, you might use the XYZ coordinates as input features.

**Comment by davodogster** [comment]
Thanks, and what about the head of the model, can it be changed to work with my data? I have one value to estimate per point cloud, instead of one value per point.

Thanks, Sam
________________________________

**Comment by zhijian-liu** [comment]
As for the head, you can do an average pooling and add a linear layer after that.
