### ISSUE TITLE
Any way of extracting the input output coordinates?

### ISSUE THREAD

**Issue by aniqueakhtar** [mit-han-lab/torchsparse#145]
Hello,
Thank you for your efforts in this library. I have a very specific problem and I was wondering if it can be resolved using torchsparse.
I am trying to use a moving window coordinate extractor. Specifically, if my input is a 3D point cloud, I would like to extract non-overlapping coordinates and their corresponding features using a 32x32x32 kernel/window.

I would like to use something like a kernel_map. Where I use a kernel of size 32x32x32 with a stride of 32. I would like to obtain all the coordinates and their corresponding features by moving this kernel over the point cloud.

This would essentially divide the tensor into non-overlapping patches. 

Any way of doing this?
Please let me know what I would need to edit in this library to obtain such functionality.
Thank you.

**Comment by zhijian-liu** [comment]
I think for your use case, a better implementation would be to first quantize the coordinates (dividing by 32) and sort the quantized coordinates of all points (so that the points within the same window will be next to each other).

**Comment by aniqueakhtar** [comment]
Thanks for the reply. I understand that dividing by 32 and sorting them would get me the downsampled coordinates. So the questions would be:
1) Any way to obtain the upsampled coordinates within the 32x32x32 window?
2) Is it possible there is a faster implementation of doing this. Doing all this in python is computationally intensive. Is there an implementation of sorting and extracting coordinates rather than me having to write a code in python?

Thank you.

**Comment by aniqueakhtar** [comment]
I have tried two methods to solve this problem. I am employing MinkowskiEngine to try to solve this.

Method # 1:
```
input_coords = x.C.cpu().numpy()
input_feats = x.F
vector = [1, 32, 32, 32]

ds_coords = input_coords // vector
unique_coords = np.unique(ds_coords, axis=0)
feats_1_out = torch.empty(input_feats.size()).to(device)

# Processing
for un in unique_coords:
    indx = np.where((ds_coords==un).all(axis=1))[0]
    out_F, _ = Process(input_feats[indx])
    feats_1_out[indx] = out_F
```

Method # 2:
```
kernel_maps = manager.kernel_map(
            key,
            stride_key,
            [1]*D,                      # Stride
            [kernel_size]*D,            # Kernel size
            [1]*D,                      # Dilation
            ME.RegionType.HYPER_CUBE,
            torch.IntTensor(),
            False,
            True,
        )

# Creating a dictionary of input and output coordinates from the kernel map
d = {}
for index in kernel_maps.keys():
    for j in range(len(kernel_maps[index][0])):
        o = int(kernel_maps[index][1,j])
        i = int(kernel_maps[index][0,j])
        d.setdefault(o,[]).append(i)

# Processing
feats_1_out = torch.empty(x.F.size()).to(device)
for i,o in enumerate(d1):
    out_F, _ = Process(x.F[d1[o]])
    feats_1_out[d1[o]] = out_F
```

The first method is pretty slow. The second method is a little better because of the kernel map but creating a dictionary from the kernel map takes a long time and thus slows down the code for practical usage.

Any tips on how this could be done? Is there any implementation of this in this library?
Thanks

**Comment by zhijian-liu** [comment]
Thanks for following up! I don't see an easy way to optimize this. The best way I can think of is to write a custom CUDA kernel based on your second method (to parallelize over `unique_coords`). It also depends a lot on the data distribution: e.g., how many points are there within each window, whether the points are uniformly distributed in different windows.
