### ISSUE TITLE
Could you upload MinkUNet18C implemented with torchsparse?

### ISSUE THREAD

**Issue by YJYJLee** [mit-han-lab/torchsparse#147]
I am trying to reproduce the result of torchsparse version of MinkowskiEngine reported in the paper and README.

Could you please upload MinkUNet18C in torchsparse version that you used at the experiment?

I am struggling to implement MinkUNet18C  with torchsparse since I am new to this library. 
It will be very helpful if I could see the author's implementation!

**Comment by zhijian-liu** [comment]
@YJYJLee, thanks for your interest! We are actively working on the new release that will contain the model zoo (with MinkUNet). Stay tuned!
