### ISSUE TITLE
Are there any suggestions for installing Google's sparse hash map project, if I am not a root user. 

### ISSUE THREAD

**Issue by jialeli1** [mit-han-lab/torchsparse#15]
Are there any suggestions for installing Google's sparse hash map project, if I am not a root user. 
When I was trying to compile and install it locally, I still encountered permission issues. Can you give me some suggestions?
> make  install-am
make[1]: Entering directory '/home/lijiale/envs_openpcdet2/sparsehash'
make[2]: Entering directory '/home/lijiale/envs_openpcdet2/sparsehash'
test -z "/usr/local/lib" || /bin/mkdir -p "/usr/local/lib"
test -z "/usr/local/share/doc/sparsehash-2.0.2" || /bin/mkdir -p "/usr/local/share/doc/sparsehash-2.0.2"
/bin/mkdir: cannot create directory ‘/usr/local/share/doc/sparsehash-2.0.2’: Permission denied
Makefile:692: recipe for target 'install-dist_docDATA' failed
make[2]: *** [install-dist_docDATA] Error 1
make[2]: Leaving directory '/home/lijiale/envs_openpcdet2/sparsehash'
Makefile:1144: recipe for target 'install-am' failed
make[1]: *** [install-am] Error 2
make[1]: Leaving directory '/home/lijiale/envs_openpcdet2/sparsehash'
Makefile:1138: recipe for target 'install' failed
make: *** [install] Error 2

Thanks.

**Comment by zhijian-liu** [comment]
Hi, you can install it into a local lib (e.g., ~/.local/lib) following https://stackoverflow.com/questions/3239343/make-install-but-not-to-default-directories.

**Comment by jialeli1** [comment]
Thanks for your kind suggestions.  I successfully installed sparsehash and torchsparse.

**Comment by songw-zju** [comment]
Hi, after make install, how do you set in your ~/.bashrc
