### ISSUE TITLE
Benchmarks from paper with spconv

### ISSUE THREAD

**Issue by oliver-batchelor** [mit-han-lab/torchsparse#152]
Hi there,

I read your recently published paper - is the benchmark available to run?

"latest versions of two state-of-the-art sparse convo-
lution libraries MinkowskiEngine v0.5.4 (Choy et al., 2019)
and SpConv v1.2.1".

Presumably the paper was written some time ago, as the SpConv latest version is now 2.1 and advertises some big performance gains.

**Comment by zhijian-liu** [comment]
Hi @oliver-batchelor, we might not release the benchmark soon since it requires a complicated dataset setup.
