### ISSUE TITLE
About GlobalMaxPool Module

### ISSUE THREAD

**Issue by suyunzzz** [mit-han-lab/torchsparse#153]
https://github.com/mit-han-lab/torchsparse/blob/67c90d17d05f8ef1e4c7c613c510fb037d4dad99/torchsparse/nn/modules/pooling.py#L15

This Module's Output is not SparseTensor but Tensor!

**Comment by zhijian-liu** [comment]
Thanks for reporting this issue! I've submitted a PR to fix the type annotation.
