### ISSUE TITLE
[Feature request] Inverse mapping from SparseTensor to point cloud (after convolution). 

### ISSUE THREAD

**Issue by kavisha725** [mit-han-lab/torchsparse#157]
Thanks for releasing this very useful library. 

Is there a way to map SparseTensor back to point cloud? 
For example, I'm trying to extract the SparseTensor at the bottleneck level of the UNet used in SPVNAS (https://github.com/mit-han-lab/spvnas/blob/69750e900d8687ac9fcc8e042b171cd1f6beffa1/core/models/semantic_kitti/spvnas.py#L322) and decompose that into the point cloud and associated point features. This involves mapping the coordinates (x4.C) back into the point values of the original point cloud. Is there a recommended way to do this? 

Thanks,
Kavisha

**Comment by zhijian-liu** [comment]
I think you could try to use devoxelization to convert the voxels at the bottleneck back to the points (see https://github.com/mit-han-lab/spvnas/blob/master/core/models/semantic_kitti/spvnas.py#L325).

**Comment by kavisha725** [comment]
Thanks for the quick reply. Sorry I forgot to include this in my earlier message. 
I'm trying to extract the points at the (down-sampled) resolution of the bottleneck level. ie. I want to convert x4.C into points and keep the same number of elements as x4.C. 

`z1 = voxel_to_point(x4, z0)` returns a PointTensor in the original resolution (same number of elements as z0).

I tried the following:
`x4_pt = PointTensor(x4.F, x4.C.float())`
`x4_pt2 = voxel_to_point(x4, x4_pt)`

which gives me 2 PointTensors of the same resolution as x4. I'm still not able to map their coordinates (x4_pt.C and x4_pt2.C) into the associated points in the original point cloud. Is this possible?

**Comment by zhijian-liu** [comment]
I still do not fully understand your use case. From my understanding, `x4_pt` is already in the point representation and has the same number of elements as `x4`.

**Comment by kavisha725** [comment]
Sorry again for the poor explanation. 
The coordinate values of SparseTensor and PointTensor variables are not the points in the original point cloud (they have been quantized). While its possible to map the coordinates of the original SparseTensor (x.C) back to the point cloud using the inverse_indices from the sparse_quantize() function (https://github.com/mit-han-lab/torchsparse/blob/4fa67d2f728fa78b1748ba065b0e6ff1ae528eea/torchsparse/utils/quantize.py#L36), is it possible to do the same reverse mapping to downsampled SparseTensors after convolution (eg. x4)?

For each value in x4.C, is it possible to get the index value of the original point cloud it corresponds to?

**Comment by zhijian-liu** [comment]
It's not natively supported. From my understanding, this mapping can be obtained by composing the following two:
* Mapping from the downsampled sparse tensor to the input sparse tensor (this could be achieved by `voxel_to_point`).
* Mapping from the input sparse tensor to the original point cloud (this can be obtained by `inverse_indices`).

**Comment by kavisha725** [comment]
Thanks for the reply. Closing the issue.
