### ISSUE TITLE
CUDA arch (8.6) installation

### ISSUE THREAD

**Issue by BlarkLee** [mit-han-lab/torchsparse#158]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you followed all the steps in the FAQ?

- [X] I have tried the steps in the FAQ.

### Current Behavior

I am using 3090Ti for installing torchsparse, I wonder if this repo is compatible with arch 86.

### Error Line

ValueError: Unknown CUDA arch (8.6) or GPU not supported

### Environment

```markdown
- GCC:7.5.0
- NVCC:10.2
- PyTorch:1.6.0
- PyTorch CUDA: 10.2
```

### Full Error Log

<details>
  <summary>Error Log</summary>

  [PUT YOUR ERROR LOG HERE]
</details>

**Comment by HeCraneChen** [comment]
How did you solve it? Had the same problem with 3090. Environment is identical to yours.
