### ISSUE TITLE
Unused variable in cuda kernel kernel_hash_kernel

### ISSUE THREAD

**Issue by ahmedius2** [mit-han-lab/torchsparse#162]
In file backend/hash/hash_cuda.cu, the following variable appears unused for the hash calculation:
`extern __shared__ int kernel_offset_local[];
`
Am I missing something or is this variable supposed to be used in place of the kernel_offset?

**Comment by kentang-mit** [comment]
I think you are right, this shared memory buffer is not used in the current implementation. In practice `kernel_offset` is a very small tensor, so it should be loaded into L1 cache automatically and it is unnecessary to specify this shared memory buffer.
