### ISSUE TITLE
Reproducing results in the paper

### ISSUE THREAD

**Issue by ahmedius2** [mit-han-lab/torchsparse#165]
Hello,

How can we reproduce the results in the TorchSparse paper at Figure 11? Do you provide the implementation of MinkUNet and CenterPoint that utilizes TorchSparse?

Also, when I look at the CUDA sparse convolution code, it appears that your adaptive grouping strategy is not implemented. Could you tell me where should I look for it, is there a specific branch?

**Comment by zhijian-liu** [comment]
Hi @ahmedius2, thanks for your interest in our work. We have a development branch for the features related to MLSys 2022, which we are currently cleaning up and verifying the correctness. Stay tuned!

**Comment by zeyu-hello** [comment]
@Xiuyu-Li Any progress of adaptive matrix multiplication grouping yet?

**Comment by haiduo** [comment]
Mark!

**Comment by Xiuyu-Li** [comment]
@ahmedius2 @zeyu-hello @haiduo The latest main branch contains our adaptive matrix multiplication grouping strategy now. You can take a look at https://github.com/mit-han-lab/torchsparse/blob/36ca82457a053207ecb31578badb887e8356a482/examples/example.py#L98-L108 for a basic example usage. More detailed documentations and an official package will be released soon.
