### ISSUE TITLE
[Installation] AttributeError: module 'torchsparse.backend' has no attribute 'hash_cuda'

### ISSUE THREAD

**Issue by saltoricristiano** [mit-han-lab/torchsparse#167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you followed all the steps in the FAQ?

- [X] I have tried the steps in the FAQ.

### Current Behavior

I installed torchsparse successfully but once I run my code, it says me `torchsparse.backend` has not `hash_cuda`. Indeed there's no `hash_cuda` in `backend.py`. I guess the error is that I'm using cudatoolkit through conda. However, the spvnas installation suggests to install everything through conda. Any solution? How can I enable the GPU compliation without a system-wise CUDA installation?

### Error Line

AttributeError: module 'torchsparse.backend' has no attribute 'hash_cuda'

### Environment

```markdown
- GCC:
- NVCC:
- PyTorch:
- PyTorch CUDA:
```

### Full Error Log

<details>
  <summary>Error Log</summary>

  [PUT YOUR ERROR LOG HERE]
</details>

**Comment by zhijian-liu** [comment]
I would recommend installing CUDA at the system level to make the installation easier.
