### ISSUE TITLE
Does torchsparse supports 16-bit training ?

### ISSUE THREAD

**Issue by tchaton** [mit-han-lab/torchsparse#17]
Dear All,

I am currently adding Pytorch Lightning support to TorchPoints3d.

If TorchSparse was to support 16-bit and be scriptable, we could have a pretty decent speed up and people would have strong reason to use torchsparse for production. 

Here is the PR: https://github.com/nicolas-chaulet/torch-points3d/pull/528

Also, here are updates from our previous release. We support ME and torchsparse backends + possible conversion between them.

<img width="870" alt="Screenshot 2021-01-02 at 13 00 37" src="https://user-images.githubusercontent.com/12861981/103456874-9fb66d80-4cfa-11eb-89b2-d73d991ae4a7.png">

Best regards,
Thomas Chaton.

**Comment by zhijian-liu** [comment]
Thanks for the great work! The current version does not support FP16, but we are actively working on incorporating FP16 into the library. We will let you know once we have some results.

**Comment by YoushaaMurhij** [comment]
@zhijian-liu. Thanks for your amazing work! Any updates on FP16 support in the library? It would be much faster if we can use model.half() and inputs.half() like in Pytorch.
