### ISSUE TITLE
[Installation] <subprocess error>

### ISSUE THREAD

**Issue by jliellen** [mit-han-lab/torchsparse#174]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you followed all the steps in the FAQ?

- [X] I have tried the steps in the FAQ.

### Current Behavior

Hi there, I had very hard time installing torch-sparse==0.6.12. I've tried many solutions online but seem like they are not working for me. Below is my command which I did under conda env:

`$ pip install torch-sparse==0.6.12 -f https://data.pyg.org/whl/torch-1.14.0+cu116.html`

I've also tried the following:
`$ pip install --verbose torch-sparse==0.6.12 -f https://data.pyg.org/whl/torch-1.9.0+cu111.html --no-cache-dir`
It successfully installed but when I ran the code, it gave me segmentation errors. So I don't think it's the right way to solve the problem.

Thank you so much in advance.

### Error Line

Some errors: 

`error: subprocess-exited-with-error`
  `× python setup.py bdist_wheel did not run successfully.`

`ERROR: Failed building wheel for torch-sparse`
`Running setup.py clean for torch-sparse`
`Failed to build torch-sparse`
`Installing collected packages: torch-sparse`
  `Running setup.py install for torch-sparse ... error`
 ` error: subprocess-exited-with-error`
`  × Running setup.py install for torch-sparse did not run successfully.`

### Environment

```markdown
- GCC: 7.5.0
- NVCC: Cuda compilation tools, release 11.6, V11.6.112 Build cuda_11.6.r11.6/compiler.30978841_0
- PyTorch: 1.14.0.dev20221011+cu116
- PyTorch CUDA: 11.6
```

### Full Error Log

<details>
  <summary>Error Log</summary>

[</details>]
[error log.txt](https://github.com/mit-han-lab/torchsparse/files/9761577/error.log.txt)

**Comment by zhijian-liu** [comment]
Since TorchSparse has been upgraded to v2.1.0, could you please attempt to install the latest version? I will now close this issue, but please don't hesitate to reopen it if the problem persists.
