### ISSUE TITLE
Add torch to requirements

### ISSUE THREAD

**Issue by neverix** [mit-han-lab/torchsparse#175]
Right now the installation implicitly requires torch. I ran into a problem because `requirements.txt` did not have torch listed 😅

**Comment by zhijian-liu** [comment]
Thanks for reporting this! We are actually working on improving the installation flow recently. Stay tuned for updates!

**Comment by zhijian-liu** [comment]
Since TorchSparse has been upgraded to v2.1.0, could you please attempt to install the latest version? I will now close this issue, but please don't hesitate to reopen it if the problem persists.

**Comment by neverix** [comment]
This is still an issue. The problem was that `requirements.txt` did not include `torch` as one of the requirements. I still can't see it in the file.
