### ISSUE TITLE
g++ error

### ISSUE THREAD

**Issue by three-nine** [mit-han-lab/torchsparse#176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you followed all the steps in the FAQ?

- [X] I have tried the steps in the FAQ.

### Current Behavior

when i execute "pip install git+https://github.com/mit-han-lab/torchsparse.git",there is a problem.And i tried "export CXX=g++".it seems not to work. 

### Error Line

Collecting git+https://github.com/mit-han-lab/torchsparse.git
  Cloning https://github.com/mit-han-lab/torchsparse.git to ./pip-req-build-6z31_v4f
  Running command git clone --filter=blob:none --quiet https://github.com/mit-han-lab/torchsparse.git /tmp/pip-req-build-6z31_v4f
  Resolved https://github.com/mit-han-lab/torchsparse.git to commit 6719899f1acff9a0395ad7bdb5b82b73c39d59d4
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: torchsparse
  Building wheel for torchsparse (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [87 lines of output]
      /home/syh/anaconda3/envs/neucon/lib/python3.7/site-packages/setuptools/dist.py:530: UserWarning: Normalizing '2.0.0b' to '2.0.0b0'
        warnings.warn(tmpl.format(**locals()))
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-37
      creating build/lib.linux-x86_64-cpython-37/torchsparse
      copying torchsparse/tensor.py -> build/lib.linux-x86_64-cpython-37/torchsparse
      copying torchsparse/operators.py -> build/lib.linux-x86_64-cpython-37/torchsparse
      copying torchsparse/version.py -> build/lib.linux-x86_64-cpython-37/torchsparse
      copying torchsparse/__init__.py -> build/lib.linux-x86_64-cpython-37/torchsparse
      copying torchsparse/backends.py -> build/lib.linux-x86_64-cpython-37/torchsparse
      creating build/lib.linux-x86_64-cpython-37/torchsparse/backbones
      copying torchsparse/backbones/__init__.py -> build/lib.linux-x86_64-cpython-37/torchsparse/backbones
      copying torchsparse/backbones/unet.py -> build/lib.linux-x86_64-cpython-37/torchsparse/backbones
      copying torchsparse/backbones/resnet.py -> build/lib.linux-x86_64-cpython-37/torchsparse/backbones
      creating build/lib.linux-x86_64-cpython-37/torchsparse/utils
      copying torchsparse/utils/utils.py -> build/lib.linux-x86_64-cpython-37/torchsparse/utils
      copying torchsparse/utils/tune.py -> build/lib.linux-x86_64-cpython-37/torchsparse/utils
      copying torchsparse/utils/quantize.py -> build/lib.linux-x86_64-cpython-37/torchsparse/utils
      copying torchsparse/utils/collate.py -> build/lib.linux-x86_64-cpython-37/torchsparse/utils
      copying torchsparse/utils/__init__.py -> build/lib.linux-x86_64-cpython-37/torchsparse/utils
      creating build/lib.linux-x86_64-cpython-37/torchsparse/nn
      copying torchsparse/nn/__init__.py -> build/lib.linux-x86_64-cpython-37/torchsparse/nn
      creating build/lib.linux-x86_64-cpython-37/torchsparse/backbones/modules
      copying torchsparse/backbones/modules/blocks.py -> build/lib.linux-x86_64-cpython-37/torchsparse/backbones/modules
      copying torchsparse/backbones/modules/__init__.py -> build/lib.linux-x86_64-cpython-37/torchsparse/backbones/modules
      creating build/lib.linux-x86_64-cpython-37/torchsparse/nn/modules
      copying torchsparse/nn/modules/activation.py -> build/lib.linux-x86_64-cpython-37/torchsparse/nn/modules
      copying torchsparse/nn/modules/bev.py -> build/lib.linux-x86_64-cpython-37/torchsparse/nn/modules
      copying torchsparse/nn/modules/norm.py -> build/lib.linux-x86_64-cpython-37/torchsparse/nn/modules
      copying torchsparse/nn/modules/__init__.py -> build/lib.linux-x86_64-cpython-37/torchsparse/nn/modules
      copying torchsparse/nn/modules/conv.py -> build/lib.linux-x86_64-cpython-37/torchsparse/nn/modules
      copying torchsparse/nn/modules/crop.py -> build/lib.linux-x86_64-cpython-37/torchsparse/nn/modules
      copying torchsparse/nn/modules/pooling.py -> build/lib.linux-x86_64-cpython-37/torchsparse/nn/modules
      creating build/lib.linux-x86_64-cpython-37/torchsparse/nn/utils
      copying torchsparse/nn/utils/__init__.py -> build/lib.linux-x86_64-cpython-37/torchsparse/nn/utils
      copying torchsparse/nn/utils/kernel.py -> build/lib.linux-x86_64-cpython-37/torchsparse/nn/utils
      copying torchsparse/nn/utils/apply.py -> build/lib.linux-x86_64-cpython-37/torchsparse/nn/utils
      creating build/lib.linux-x86_64-cpython-37/torchsparse/nn/functional
      copying torchsparse/nn/functional/build_kmap.py -> build/lib.linux-x86_64-cpython-37/torchsparse/nn/functional
      copying torchsparse/nn/functional/activation.py -> build/lib.linux-x86_64-cpython-37/torchsparse/nn/functional
      copying torchsparse/nn/functional/devoxelize.py -> build/lib.linux-x86_64-cpython-37/torchsparse/nn/functional
      copying torchsparse/nn/functional/count.py -> build/lib.linux-x86_64-cpython-37/torchsparse/nn/functional
      copying torchsparse/nn/functional/voxelize.py -> build/lib.linux-x86_64-cpython-37/torchsparse/nn/functional
      copying torchsparse/nn/functional/__init__.py -> build/lib.linux-x86_64-cpython-37/torchsparse/nn/functional
      copying torchsparse/nn/functional/conv.py -> build/lib.linux-x86_64-cpython-37/torchsparse/nn/functional
      copying torchsparse/nn/functional/downsample.py -> build/lib.linux-x86_64-cpython-37/torchsparse/nn/functional
      copying torchsparse/nn/functional/crop.py -> build/lib.linux-x86_64-cpython-37/torchsparse/nn/functional
      copying torchsparse/nn/functional/hash.py -> build/lib.linux-x86_64-cpython-37/torchsparse/nn/functional
      copying torchsparse/nn/functional/query.py -> build/lib.linux-x86_64-cpython-37/torchsparse/nn/functional
      copying torchsparse/nn/functional/pooling.py -> build/lib.linux-x86_64-cpython-37/torchsparse/nn/functional
      running build_ext
      building 'torchsparse.backend' extension
      creating /tmp/pip-req-build-6z31_v4f/build/temp.linux-x86_64-cpython-37
      creating /tmp/pip-req-build-6z31_v4f/build/temp.linux-x86_64-cpython-37/torchsparse
      creating /tmp/pip-req-build-6z31_v4f/build/temp.linux-x86_64-cpython-37/torchsparse/backend
      creating /tmp/pip-req-build-6z31_v4f/build/temp.linux-x86_64-cpython-37/torchsparse/backend/convolution
      creating /tmp/pip-req-build-6z31_v4f/build/temp.linux-x86_64-cpython-37/torchsparse/backend/devoxelize
      creating /tmp/pip-req-build-6z31_v4f/build/temp.linux-x86_64-cpython-37/torchsparse/backend/hash
      creating /tmp/pip-req-build-6z31_v4f/build/temp.linux-x86_64-cpython-37/torchsparse/backend/hashmap
      creating /tmp/pip-req-build-6z31_v4f/build/temp.linux-x86_64-cpython-37/torchsparse/backend/others
      creating /tmp/pip-req-build-6z31_v4f/build/temp.linux-x86_64-cpython-37/torchsparse/backend/voxelize
      Emitting ninja build file /tmp/pip-req-build-6z31_v4f/build/temp.linux-x86_64-cpython-37/build.ninja...
      Compiling objects...
      Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
      1.10.2
      g++ -pthread -shared -B /home/syh/anaconda3/envs/neucon/compiler_compat -L/home/syh/anaconda3/envs/neucon/lib -Wl,-rpath=/home/syh/anaconda3/envs/neucon/lib -Wl,--no-as-needed -Wl,--sysroot=/ /tmp/pip-req-build-6z31_v4f/build/temp.linux-x86_64-cpython-37/torchsparse/backend/convolution/convolution_cpu.o /tmp/pip-req-build-6z31_v4f/build/temp.linux-x86_64-cpython-37/torchsparse/backend/convolution/convolution_cuda.o /tmp/pip-req-build-6z31_v4f/build/temp.linux-x86_64-cpython-37/torchsparse/backend/devoxelize/devoxelize_cpu.o /tmp/pip-req-build-6z31_v4f/build/temp.linux-x86_64-cpython-37/torchsparse/backend/devoxelize/devoxelize_cuda.o /tmp/pip-req-build-6z31_v4f/build/temp.linux-x86_64-cpython-37/torchsparse/backend/hash/hash_cpu.o /tmp/pip-req-build-6z31_v4f/build/temp.linux-x86_64-cpython-37/torchsparse/backend/hash/hash_cuda.o /tmp/pip-req-build-6z31_v4f/build/temp.linux-x86_64-cpython-37/torchsparse/backend/hashmap/hashmap_cpu.o /tmp/pip-req-build-6z31_v4f/build/temp.linux-x86_64-cpython-37/torchsparse/backend/hashmap/hashmap_cuda.o /tmp/pip-req-build-6z31_v4f/build/temp.linux-x86_64-cpython-37/torchsparse/backend/others/count_cpu.o /tmp/pip-req-build-6z31_v4f/build/temp.linux-x86_64-cpython-37/torchsparse/backend/others/count_cuda.o /tmp/pip-req-build-6z31_v4f/build/temp.linux-x86_64-cpython-37/torchsparse/backend/others/downsample_cuda.o /tmp/pip-req-build-6z31_v4f/build/temp.linux-x86_64-cpython-37/torchsparse/backend/others/query_cpu.o /tmp/pip-req-build-6z31_v4f/build/temp.linux-x86_64-cpython-37/torchsparse/backend/others/query_cuda.o /tmp/pip-req-build-6z31_v4f/build/temp.linux-x86_64-cpython-37/torchsparse/backend/others/sparsemapping_cuda.o /tmp/pip-req-build-6z31_v4f/build/temp.linux-x86_64-cpython-37/torchsparse/backend/pybind_cuda.o /tmp/pip-req-build-6z31_v4f/build/temp.linux-x86_64-cpython-37/torchsparse/backend/voxelize/voxelize_cpu.o /tmp/pip-req-build-6z31_v4f/build/temp.linux-x86_64-cpython-37/torchsparse/backend/voxelize/voxelize_cuda.o -L/home/syh/anaconda3/envs/neucon/lib/python3.7/site-packages/torch/lib -L/usr/local/cuda/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -o build/lib.linux-x86_64-cpython-37/torchsparse/backend.cpython-37m-x86_64-linux-gnu.so
      g++: error: /tmp/pip-req-build-6z31_v4f/build/temp.linux-x86_64-cpython-37/torchsparse/backend/convolution/convolution_cpu.o: 没有那个文件或目录
      g++: error: /tmp/pip-req-build-6z31_v4f/build/temp.linux-x86_64-cpython-37/torchsparse/backend/convolution/convolution_cuda.o: 没有那个文件或目录
      g++: error: /tmp/pip-req-build-6z31_v4f/build/temp.linux-x86_64-cpython-37/torchsparse/backend/devoxelize/devoxelize_cpu.o: 没有那个文件或目录
      g++: error: /tmp/pip-req-build-6z31_v4f/build/temp.linux-x86_64-cpython-37/torchsparse/backend/devoxelize/devoxelize_cuda.o: 没有那个文件或目录
      g++: error: /tmp/pip-req-build-6z31_v4f/build/temp.linux-x86_64-cpython-37/torchsparse/backend/hash/hash_cpu.o: 没有那个文件或目录
      g++: error: /tmp/pip-req-build-6z31_v4f/build/temp.linux-x86_64-cpython-37/torchsparse/backend/hash/hash_cuda.o: 没有那个文件或目录
      g++: error: /tmp/pip-req-build-6z31_v4f/build/temp.linux-x86_64-cpython-37/torchsparse/backend/hashmap/hashmap_cpu.o: 没有那个文件或目录
      g++: error: /tmp/pip-req-build-6z31_v4f/build/temp.linux-x86_64-cpython-37/torchsparse/backend/hashmap/hashmap_cuda.o: 没有那个文件或目录
      g++: error: /tmp/pip-req-build-6z31_v4f/build/temp.linux-x86_64-cpython-37/torchsparse/backend/others/count_cpu.o: 没有那个文件或目录
      g++: error: /tmp/pip-req-build-6z31_v4f/build/temp.linux-x86_64-cpython-37/torchsparse/backend/others/count_cuda.o: 没有那个文件或目录
      g++: error: /tmp/pip-req-build-6z31_v4f/build/temp.linux-x86_64-cpython-37/torchsparse/backend/others/downsample_cuda.o: 没有那个文件或目录
      g++: error: /tmp/pip-req-build-6z31_v4f/build/temp.linux-x86_64-cpython-37/torchsparse/backend/others/query_cpu.o: 没有那个文件或目录
      g++: error: /tmp/pip-req-build-6z31_v4f/build/temp.linux-x86_64-cpython-37/torchsparse/backend/others/query_cuda.o: 没有那个文件或目录
      g++: error: /tmp/pip-req-build-6z31_v4f/build/temp.linux-x86_64-cpython-37/torchsparse/backend/others/sparsemapping_cuda.o: 没有那个文件或目录
      g++: error: /tmp/pip-req-build-6z31_v4f/build/temp.linux-x86_64-cpython-37/torchsparse/backend/pybind_cuda.o: 没有那个文件或目录
      g++: error: /tmp/pip-req-build-6z31_v4f/build/temp.linux-x86_64-cpython-37/torchsparse/backend/voxelize/voxelize_cpu.o: 没有那个文件或目录
      g++: error: /tmp/pip-req-build-6z31_v4f/build/temp.linux-x86_64-cpython-37/torchsparse/backend/voxelize/voxelize_cuda.o: 没有那个文件或目录
      error: command '/usr/bin/g++' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for torchsparse
  Running setup.py clean for torchsparse
Failed to build torchsparse
Installing collected packages: torchsparse
  Running setup.py install for torchsparse ... error
  error: subprocess-exited-with-error

### Environment

```markdown
- GCC:7
- NVCC:10.2
- PyTorch:1.6.0
- PyTorch CUDA:10.2
```

### Full Error Log

<details>
  <summary>Error Log</summary>

  [PUT YOUR ERROR LOG HERE]
</details>

**Comment by ssh0731** [comment]
一样！！！请问你解决了吗

**Comment by zyx-99** [comment]
> 一样！！！请问你解决了吗

遇到一样的问题，请问您解决了吗？

**Comment by slowRiver** [comment]
遇到一样的问题，请问您解决了吗？

**Comment by slowRiver** [comment]
@Xiuyu-Li @zyx-99 @three-nine 
you can try this:

git clone https://github.com/mit-han-lab/torchsparse.git && cd torchsparse run:git checkout v1.4.0
2)cd .. && pip install ./torchsparse

3)cd torchsparse/build/temp.linux-x86_64-cpython-38/

4)gedit build.ninja (change -03 to -std=c++17 or -std=c++14)
like this:
"
ninja_required_version = 1.3
cxx = c++
nvcc = /usr/local/cuda/bin/nvcc

cflags = -pthread -B /home/dh/anaconda3/envs/my_openmmlab/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/dh/anaconda3/envs/my_openmmlab/lib/python3.8/site-packages/torch/include -I/home/dh/anaconda3/envs/my_openmmlab/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/dh/anaconda3/envs/my_openmmlab/lib/python3.8/site-packages/torch/include/TH -I/home/dh/anaconda3/envs/my_openmmlab/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/dh/anaconda3/envs/my_openmmlab/include/python3.8 -c
post_cflags = -g -O3 -fopenmp -lgomp -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="gcc"' '-DPYBIND11_STDLIB="libstdcpp"' '-DPYBIND11_BUILD_ABI="cxxabi1011"' -DTORCH_EXTENSION_NAME=backend -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++17
cuda_cflags = -I/home/dh/anaconda3/envs/my_openmmlab/lib/python3.8/site-packages/torch/include -I/home/dh/anaconda3/envs/my_openmmlab/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/dh/anaconda3/envs/my_openmmlab/lib/python3.8/site-packages/torch/include/TH -I/home/dh/anaconda3/envs/my_openmmlab/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/dh/anaconda3/envs/my_openmmlab/include/python3.8 -c
cuda_post_cflags = -D__CUDA_NO_HALF_OPERATORS -D__CUDA_NO_HALF_CONVERSIONS_ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=backend -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++17
cuda_dlink_post_cflags =
ldflags =

rule compile
command = $cxx -MMD -MF $out.d $cflags -c $in -o $out $post_cflags
depfile = $out.d
deps = gcc

rule cuda_compile
depfile = $out.d
deps = gcc
command = $nvcc $cuda_cflags -c $in -o $out $cuda_post_cflags

build /home/dh/mmdetection3d/opencode/torchsparse/build/temp.linux-x86_64-cpython-38/torchsparse/backend/convolution/convolution_cpu.o: compile /home/dh/mmdetection3d/opencode/torchsparse/torchsparse/backend/convolution/convolution_cpu.cpp
build /home/dh/mmdetection3d/opencode/torchsparse/build/temp.linux-x86_64-cpython-38/torchsparse/backend/convolution/convolution_cuda.o: cuda_compile /home/dh/mmdetection3d/opencode/torchsparse/torchsparse/backend/convolution/convolution_cuda.cu
build /home/dh/mmdetection3d/opencode/torchsparse/build/temp.linux-x86_64-cpython-38/torchsparse/backend/devoxelize/devoxelize_cpu.o: compile /home/dh/mmdetection3d/opencode/torchsparse/torchsparse/backend/devoxelize/devoxelize_cpu.cpp
build /home/dh/mmdetection3d/opencode/torchsparse/build/temp.linux-x86_64-cpython-38/torchsparse/backend/devoxelize/devoxelize_cuda.o: cuda_compile /home/dh/mmdetection3d/opencode/torchsparse/torchsparse/backend/devoxelize/devoxelize_cuda.cu
build /home/dh/mmdetection3d/opencode/torchsparse/build/temp.linux-x86_64-cpython-38/torchsparse/backend/hash/hash_cpu.o: compile /home/dh/mmdetection3d/opencode/torchsparse/torchsparse/backend/hash/hash_cpu.cpp
build /home/dh/mmdetection3d/opencode/torchsparse/build/temp.linux-x86_64-cpython-38/torchsparse/backend/hash/hash_cuda.o: cuda_compile /home/dh/mmdetection3d/opencode/torchsparse/torchsparse/backend/hash/hash_cuda.cu
build /home/dh/mmdetection3d/opencode/torchsparse/build/temp.linux-x86_64-cpython-38/torchsparse/backend/hashmap/hashmap_cpu.o: compile /home/dh/mmdetection3d/opencode/torchsparse/torchsparse/backend/hashmap/hashmap_cpu.cpp
build /home/dh/mmdetection3d/opencode/torchsparse/build/temp.linux-x86_64-cpython-38/torchsparse/backend/hashmap/hashmap_cuda.o: cuda_compile /home/dh/mmdetection3d/opencode/torchsparse/torchsparse/backend/hashmap/hashmap_cuda.cu
build /home/dh/mmdetection3d/opencode/torchsparse/build/temp.linux-x86_64-cpython-38/torchsparse/backend/others/count_cpu.o: compile /home/dh/mmdetection3d/opencode/torchsparse/torchsparse/backend/others/count_cpu.cpp
build /home/dh/mmdetection3d/opencode/torchsparse/build/temp.linux-x86_64-cpython-38/torchsparse/backend/others/count_cuda.o: cuda_compile /home/dh/mmdetection3d/opencode/torchsparse/torchsparse/backend/others/count_cuda.cu
build /home/dh/mmdetection3d/opencode/torchsparse/build/temp.linux-x86_64-cpython-38/torchsparse/backend/others/query_cpu.o: compile /home/dh/mmdetection3d/opencode/torchsparse/torchsparse/backend/others/query_cpu.cpp
build /home/dh/mmdetection3d/opencode/torchsparse/build/temp.linux-x86_64-cpython-38/torchsparse/backend/others/query_cuda.o: cuda_compile /home/dh/mmdetection3d/opencode/torchsparse/torchsparse/backend/others/query_cuda.cu
build /home/dh/mmdetection3d/opencode/torchsparse/build/temp.linux-x86_64-cpython-38/torchsparse/backend/pybind_cuda.o: compile /home/dh/mmdetection3d/opencode/torchsparse/torchsparse/backend/pybind_cuda.cpp
build /home/dh/mmdetection3d/opencode/torchsparse/build/temp.linux-x86_64-cpython-38/torchsparse/backend/voxelize/voxelize_cpu.o: compile /home/dh/mmdetection3d/opencode/torchsparse/torchsparse/backend/voxelize/voxelize_cpu.cpp
build /home/dh/mmdetection3d/opencode/torchsparse/build/temp.linux-x86_64-cpython-38/torchsparse/backend/voxelize/voxelize_cuda.o: cuda_compile /home/dh/mmdetection3d/opencode/torchsparse/torchsparse/backend/voxelize/voxelize_cuda.cu

"

5)ninja -j8

6)cd .. && cd .. && cd ..

7)pip install ./torchsparse
"
Processing ./torchsparse
Preparing metadata (setup.py) ... done
Building wheels for collected packages: torchsparse
Building wheel for torchsparse (setup.py) ... done
Created wheel for torchsparse: filename=torchsparse-1.4.0-cp38-cp38-linux_x86_64.whl size=14330217 sha256=c921b618f030f9caaaeb460405c883fb53ee8d0f7f6e78d79ad320279b5405a1
Stored in directory: /tmp/pip-ephem-wheel-cache-t_vkeku1/wheels/1c/c6/85/b204cc246ca8470c90a61d5aaa2989c4323c1f98327b74e406
Successfully built torchsparse
Installing collected packages: torchsparse
Successfully installed torchsparse-1.4.0
"

应该是ninja 出问题了，只能大力出奇迹

**Comment by zhijian-liu** [comment]
Since TorchSparse has been upgraded to v2.1.0, could you please attempt to install the latest version? I will now close this issue, but please don't hesitate to reopen it if the problem persists.
