### ISSUE TITLE
It seem there is some problem while using torchsparse with nn.DataParallel

### ISSUE THREAD

**Issue by HilbertXu** [mit-han-lab/torchsparse#18]
Hi all, 

Thanks for your amazing torchsparse library! 

I am currently deploy a large model for 3D object detection, and my GPU(RTX Titan) does not have enough memory to train my model, so i want to use nn.DataParallel to distribute my model on two RTX Titan. However, part of my model uses torchsparse and it returns erro like this:

>AssertionError: Caught AssertionError in replica 0 on device 0.
>Original Traceback (most recent call last):
>  File "/home/user/anaconda3/envs/cupcl/lib/python3.7/site-packages/torchsparse/nn/functional/sparseconv.py", line 173, in conv3d
>    kOffset = kRegion.get_kernel_offset().cuda()
> RuntimeError: CUDA error: an illegal memory access was encountered

Since this is the first time I use nn.DataParallel in my project, I dont know how to solve this problem. I simply modified .to(feature.device) to .cuda() but makes no different. Waiting for your help, thanks!

**Comment by zhijian-liu** [comment]
It might be a little bit hard (and actually less efficient) to use `nn.DataParallel` due to the format of `SparseTensor`. Instead, it's preferred to use `nn.DistributedDataParallel` (see https://github.com/mit-han-lab/e3d/tree/master/spvnas for more details).

**Comment by HilbertXu** [comment]
Hi Liu, 

Thanks for your reply, I will try to use the nn.DistributedDataParallel in my project.

Have a nice day!
