### ISSUE TITLE
[Installation] < Snapdragon Neural Processing Engine>

### ISSUE THREAD

**Issue by xuyongzhi** [mit-han-lab/torchsparse#182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you followed all the steps in the FAQ?

- [X] I have tried the steps in the FAQ.

### Current Behavior

I am wondering if torchsparse can be supported by Snapdragon Neural Processing Engine

### Error Line

Unknown

### Environment

```markdown
Snapdragon Neural Processing Engine 
https://developer.qualcomm.com/sites/default/files/docs/snpe/network_layers.html
```

### Full Error Log

<details>
  <summary>Error Log</summary>

  [PUT YOUR ERROR LOG HERE]
</details>

**Comment by zhijian-liu** [comment]
TorchSparse does not support SNPE for now.
