### ISSUE TITLE
Generative Transposed Convolution

### ISSUE THREAD

**Issue by YilmazKadir** [mit-han-lab/torchsparse#188]
I checked torchsparse.nn.Conv3d and could not find generative or expand_coordinates flag. Do you provide 3D generative transposed convolution operation that allows to create new possible coordinates as in Minkowski Engine: https://github.com/NVIDIA/MinkowskiEngine/blob/b71caef9b45ab32c02d2c1b5f48f13c1eb5df526/MinkowskiEngine/MinkowskiConvolution.py#L539
If not do you plan to add support for this operation which is very crucial for 3D sparse reconstruction tasks?

**Comment by zhijian-liu** [comment]
Thanks for letting us know! This is not supported yet but is definitely in our plan. Stay tuned!

**Comment by zhijian-liu** [comment]
@kentang-mit do we have an implementation of this in v2.1.0?
