### ISSUE TITLE
[BUG] <hash_query_cuda get some abnormal values in the returned tensor >

### ISSUE THREAD

**Issue by Peeta586** [mit-han-lab/torchsparse#192]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

- the file is query_cuda.cu
- the problem is :
> when I use the bottleneck block in my neural network, the hash_query_cuda will return the tensor within some abnormal elements.
That is: 
The maximum element  in the returned tensor of hash_query_cuda function should be less than the number of input points, but I get some abnormal value is larger than the number of input points. 

So, I want to ask, What is the possible reasons? Thank you for your reply.

### Environment

```markdown
- GCC:
- NVCC:
- PyTorch:
- PyTorch CUDA:
- TorchSparse:
```

**Comment by zhijian-liu** [comment]
Since TorchSparse has been upgraded to v2.1.0, could you please attempt to install the latest version? I will now close this issue, but please don't hesitate to reopen it if the problem persists.
