### ISSUE TITLE
[Feature Request / Question] Pruning for sparse tensors

### ISSUE THREAD

**Issue by fabioruetz** [mit-han-lab/torchsparse#193]
Hi, 

The MinkowskiEngine provides the ability to prune layers after upsampling. Is there a similar but differently named feature in torchsparse or are there plans to implement this? 

Kindest,
fabioruetz

Pruning: https://nvidia.github.io/MinkowskiEngine/pruning.html

**Comment by zhijian-liu** [comment]
This is essentially a generative transposed convolution. See https://github.com/mit-han-lab/torchsparse/issues/188. We don't support this yet, but it's in our roadmap.

**Comment by Tortoise0Knight** [comment]
> This is essentially a generative transposed convolution. See #188. We don't support this yet, but it's in our roadmap.

May I ask how to implement pruning by generative transposed convolution in detail? I can't figure it out.
