### ISSUE TITLE
[BUG] torch.div behavior changing

### ISSUE THREAD

**Issue by fishbotics** [mit-han-lab/torchsparse#195]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running a basic model, I get the following warning:
```
/usr/local/lib/python3.8/dist-packages/torchsparse/nn/functional/downsample.py:27: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
```

### Expected Behavior

This warning should probably be dealt with before the behavior changes, unless it's already changed in a newer Pytorch in which case maybe a conditional in the code would make sense to handle different Pytorch versions

### Environment

```markdown
- GCC: 9.4.0
- NVCC: V11.3.109
- PyTorch: 1.12.0+cu113
- PyTorch CUDA: 11.3
- TorchSparse: 1.4.0
```

**Comment by zhijian-liu** [comment]
Thanks! Could you please submit a PR to fix this? I think it should probably be a one-line change.

**Comment by fishbotics** [comment]
It actually looks like this has already been fixed, but it just hasn't made it into a release yet: https://github.com/mit-han-lab/torchsparse/commit/69c1034ddb285798619380537802ea0ff03aeba6

Is there a way to cherry pick that commit into the current release or is this a "wait until the next one comes out" kind of thing?

**Comment by zhijian-liu** [comment]
You could reinstall with `pip install --upgrade git+https://github.com/mit-han-lab/torchsparse.git`.
