### ISSUE TITLE
[Installation] <title>running “pip install --user git+https://github.com/mit-han-lab/torchsparse.git” throws ERROR

### ISSUE THREAD

**Issue by eva-yx-wang** [mit-han-lab/torchsparse#199]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you followed all the steps in the FAQ?

- [X] I have tried the steps in the FAQ.

### Current Behavior

when I run "pip install --user --upgrade git+https://github.com/mit-han-lab/torchsparse.git", error occured as following:

ERROR: Command errored out with exit status 1:
     command: /home/wyx/anaconda3/envs/pctv2/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-2qad3awg/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-2qad3awg/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-sp2da79j
         cwd: /tmp/pip-req-build-2qad3awg/
    Complete output (15 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-2qad3awg/setup.py", line 10, in <module>
        from torchsparse import __version__
      File "/tmp/pip-req-build-2qad3awg/torchsparse/__init__.py", line 5, in <module>
        from .utils.tune import tune
      File "/tmp/pip-req-build-2qad3awg/torchsparse/utils/tune.py", line 14, in <module>
        from torchsparse.nn import Conv3d
      File "/tmp/pip-req-build-2qad3awg/torchsparse/nn/__init__.py", line 1, in <module>
        from .modules import *
      File "/tmp/pip-req-build-2qad3awg/torchsparse/nn/modules/__init__.py", line 3, in <module>
        from .conv import *
      File "/tmp/pip-req-build-2qad3awg/torchsparse/nn/modules/conv.py", line 8, in <module>
        from backports.cached_property import cached_property
    ModuleNotFoundError: No module named 'backports.cached_property'
    ----------------------------------------
WARNING: Discarding git+https://github.com/mit-han-lab/torchsparse.git. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output
----------------------------------------------------------------

then I do something to fix my error and successfully install torchsparse, I hope my experience can help you, thanks!
1. install dependencies
```
sudo apt-get update 
sudo apt-get install libsparsehash-dev
conda install -n pctv2 -c conda-forge backports.cached-property
```
2. "vim ~/.bashrc", append command as follow:
"export TORCH_CUDA_ARCH_LIST="8.0" "
then "source ~/.bashrc"
3. install torchsparse in conda env 
```
pip install --user --upgrade git+https://github.com/mit-han-lab/torchsparse.git@v1.4.0
```

### Error Line

-

### Environment

```markdown
- GCC:Ubuntu 9.4.0-1ubuntu1~20.04.1
- NVCC: V11.0.194
- PyTorch: 1.10.1+cu111
- PyTorch CUDA: 11.1
```

**Comment by zhijian-liu** [comment]
Thanks for sharing!
