### ISSUE TITLE
Distributed Training!

### ISSUE THREAD

**Issue by zxczrx123** [mit-han-lab/torchsparse#2]
Thanks for your nice work! 
How to use SyncBatchNorm when distirbuted training and could you give some guide about MultiGPU training?

**Comment by kentangSJTU** [comment]
Hello,

Thanks for your interest in our work! We don't use SyncBatchNorm when training our models with multiple GPUs. On Multi-GPU training, we'll be releasing official code very soon after we finalizing some details in training.

If you want to try it out now, please refer to our [e3d/spvnas](https://github.com/mit-han-lab/e3d/tree/master/spvnas) codebase for details. You may convert `evaluate.py` to a training script by deleting evaluation part and add

```python
trainer.train_with_defaults(
    dataflow['train'],
    num_epochs=configs.num_epochs,
    callbacks=[
        InferenceRunner(
            dataflow[split],
            callbacks=[MeanIoU(
                name=f'iou/{split}',
                num_classes=configs.data.num_classes,
                ignore_label=configs.data.ignore_label
            )])
        for split in ['test']
    ] + [
        MaxSaver('iou/test'),
        Saver(),
    ])
```

Finally, run this command:
```bash
torchpack dist-run -np [num_gpus] python [training_script_name].py configs/semantic_kitti/[model name]/[config name].yaml
```

Hope that solves your problem.


Best,
Haotian

**Comment by zxczrx123** [comment]
Thank you very much for your help, I have been able to train properly. By the way,approximately when will you post your training details? I'm looking forward to it.

**Comment by kentangSJTU** [comment]
> Thank you very much for your help, I have been able to train properly. By the way,approximately when will you post your training details? I'm looking forward to it.

Hi,

Training details of baseline models have been released under our [spvnas](https://github.com/mit-han-lab/e3d/tree/master/spvnas) repository. Please have a look, thanks!

Best,
Haotian
