### ISSUE TITLE
MaxPooling

### ISSUE THREAD

**Issue by weizmanl** [mit-han-lab/torchsparse#20]
Torch's maxpooling inputs a kernel. Looks like torchsparse maxpooling performs on the entire dimension. It that correct? Is there any way to use torchsparse's maxpooling with a kernel?

**Comment by zhijian-liu** [comment]
That's correct. We don't have a plan to support this in the near future as modern NN usually uses convolution with strides to downsample the input. Feel free to have a PR on this.
