### ISSUE TITLE
ERROR: bucket overflow 

### ISSUE THREAD

**Issue by Akola-Mbey-Denis** [mit-han-lab/torchsparse#200]
The solutions suggested to fix this issue in https://github.com/mit-han-lab/torchsparse/issues/55, does not solve the issue.
Is there an alternative solution for this issue?

**Comment by zhijian-liu** [comment]
Since TorchSparse has been upgraded to v2.1.0, could you please attempt to install the latest version? I will now close this issue, but please don't hesitate to reopen it if the problem persists.

**Comment by meyerjo** [comment]
I have the same problem with the latest version from the master-branch.

**Comment by LianMing345** [comment]
你好，我有相同的问题，请问您有新的解决方法吗？
