### ISSUE TITLE
[Installation] <title> how to use source code to install torchsparse?

### ISSUE THREAD

**Issue by chriscarving** [mit-han-lab/torchsparse#205]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you followed all the steps in the FAQ?

- [X] I have tried the steps in the FAQ.

### Current Behavior

Hi, I cannot use pip to install because the network. so can you add a doc about how to use source code to setup?

### Error Line

aaaa

### Environment

```markdown
- GCC: a
- NVCC:a
- PyTorch:a
- PyTorch CUDA:
a
```

### Full Error Log

<details>
  <summary>Error Log</summary>
a
  [PUT YOUR ERROR LOG HERE]a
</details>
a

**Comment by zhijian-liu** [comment]
The source code of TorchSparse 2.1.0 is currently undergoing internal quality checks. To install it, we recommend using our pre-built wheels.
