### ISSUE TITLE
[Installation] New torchsparse++ library release?

### ISSUE THREAD

**Issue by rahuja123** [mit-han-lab/torchsparse#208]
Is there a timeline to release the torchsparse++ library? Referring to the [paper here](https://openaccess.thecvf.com/content/CVPR2023W/WAD/papers/Tang_TorchSparse_Efficient_Point_Cloud_Engine_CVPRW_2023_paper.pdf)

**Comment by kentang-mit** [comment]
Hi @rahuja123,

TorchSparse++ has just been released. Thank you for your interest!

Best,
Haotian
