### ISSUE TITLE
torchsparse 2.1.0 missing PointTensor

### ISSUE THREAD

**Issue by TetraEngine** [mit-han-lab/torchsparse#213]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I just attempted to use torchsparse with NeuralRecon, and found that I am unable to proceed because PointTensor is completely missing from the package. There is no documentation as to why it was removed or where it's now located. There isn't even source code for 2.1.0, only 2.0.0. I am unable to install an older version because there are only wheels for 2.1.0 online.

### Expected Behavior

Either documentation on whereabouts or deprecation of PointTensor, replacement of PointTensor back into torchsparse (if it's an error), or access to older wheel files.

### Environment

```markdown
- GCC: 9.4.0
- NVCC: 11.7
- PyTorch: 1.13.1
- PyTorch CUDA: 11.7
- TorchSparse: 2.1.0+torch113cu117
```

**Comment by kentang-mit** [comment]
Hi @TetraEngine,

This is the expected behavior. We deprecated `PointTensor` from torchsparse because it is only used in the SPVNAS project. We instead provided a better implementation of this class in spvnas, which can be accessed [here](https://github.com/mit-han-lab/spvnas/blob/dev/torchsparsepp_backend/core/models/utils.py#L16).

Best,
Haotian

**Comment by 440981** [comment]
> 你好@TetraEngine,
> 
> 这是预期的行为。我们弃用`PointTensor`了 torchsparse，因为它仅在 SPVNAS 项目中使用。相反，我们在 spvnas 中提供了此类的更好实现，可以[在此处](https://github.com/mit-han-lab/spvnas/blob/dev/torchsparsepp_backend/core/models/utils.py#L16)访问。
> 
> 最好的， 昊天



> 你好@TetraEngine,
> 
> 这是预期的行为。我们弃用`PointTensor`了 torchsparse，因为它仅在 SPVNAS 项目中使用。相反，我们在 spvnas 中提供了此类的更好实现，可以[在此处](https://github.com/mit-han-lab/spvnas/blob/dev/torchsparsepp_backend/core/models/utils.py#L16)访问。
> 
> 最好的， 昊天

How can I introduce or use alternatives
