### ISSUE TITLE
[BUG] <Documents>

### ISSUE THREAD

**Issue by vuducquan96** [mit-han-lab/torchsparse#216]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I can't found this function [F.set_downsample_mode('spconv')	](https://torchsparse-docs.github.io/getting_started/changes.html) in your source code. I also check branch v2.1.0 and can't find it. Where can I get this function. Thank you !

**Comment by zhijian-liu** [comment]
The source code of TorchSparse 2.1.0 is currently undergoing internal quality checks. Please check our documentation for the latest APIs.

**Comment by vuducquan96** [comment]
@zhijian-liu Thanks for your information.
