### ISSUE TITLE
Problem with torchsparse.nn.functional spvoxelize

### ISSUE THREAD

**Issue by JohnRomanelis** [mit-han-lab/torchsparse#22]
Hey! 
First of all thank you for your amazing work! 

I am trying to install torchsparse to use it for a 3d object detection network. 
I am using pytorch 1.7 with cuda 11.0 and i have cuda 11.1 installed separately. 
(I use cuda 11.1 because i am using a 3090 and lower versions of cuda are not supported). 
I am also using ubuntu 20.04 and i have downgraded the gcc compiler to version 7.5.

My problem is that although i manage to successfully install torchsparse when using spf.spvoxelize the output tensor is filled with zeros. 

I tried running the example on /examples/example.py and it runs just fine. I also trained it on a single input to see if the network converges and it does. 

Is there something i could do to fix this? 

Thank you in advance!

**Comment by sinAshish** [comment]
I am also facing this same issue

**Comment by zhijian-liu** [comment]
@JohnRomanelis and @sinAshish, could you please provide a sample code to reproduce your issue? Thanks!

**Comment by JohnRomanelis** [comment]
Hello @zhijian-liu

I used the _initial_voxelize_ function provided at the e3d/spvnas/core/models/utils.py (https://github.com/mit-han-lab/e3d/blob/master/spvnas/core/models/utils.py). I create a random pointcloud, turn it to a torchsparse.PointTensor and pass it through the aforementioned function. 

Here is a code sample:
`
import torch
from torchsparse import PointTensor, SparseTensor
import torchsparse.nn.functional as spf

def initial_voxelize(z, init_res, after_res):
    new_float_coord = torch.cat(
        [(z.C[:, :3] * init_res) / after_res, z.C[:, -1].view(-1, 1)], 1)

    pc_hash = spf.sphash(torch.floor(new_float_coord).int())
    sparse_hash = torch.unique(pc_hash)
    idx_query = spf.sphashquery(pc_hash, sparse_hash)
    counts = spf.spcount(idx_query.int(), len(sparse_hash))

    inserted_coords = spf.spvoxelize(torch.floor(new_float_coord), idx_query,
                                   counts)
    inserted_coords = torch.round(inserted_coords).int()
    inserted_feat = spf.spvoxelize(z.F, idx_query, counts)

    print(inserted_coords)

    new_tensor = SparseTensor(inserted_feat, inserted_coords, 1)
    new_tensor.check()
    z.additional_features['idx_query'][1] = idx_query
    z.additional_features['counts'][1] = counts
    z.C = new_float_coord

    return new_tensor


num_points = 5
init_res = 1.0
after_res = 0.01

# create dummy pointcould
pc = torch.rand(num_points, 3)
# add _batch_dimension
pc = torch.cat([pc, torch.zeros(pc.shape[0], 1)], dim=-1)

pc = PointTensor(pc[:,:3], pc)

ret = initial_voxelize(pc, init_res, after_res)` 

And the output is:

`tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)`

**Comment by zhijian-liu** [comment]
@kentangSJTU, could you please take a look at this?

**Comment by sinAshish** [comment]
I do the foll. to create a voxel:
```python
x= torch.rand(2, 512, 3) #BxNxC
coords = torch.cat([x, x.size()[:2].unsqueeze(-1)], -1) #BxNx(C+1)
pc = SparseTensor(x, coords.int()).to(device)
z = PointTensor(pc.F, pc.C.float()).to(device)
x0 = initial_voxelize(z, 1., 0.01)
```
I get the foll. error:
```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 7, in initial_voxelize
  File "/usr/local/lib/python3.6/dist-packages/torchsparse/nn/functional/voxelize.py", line 25, in spvoxelize
    return VoxelizeGPU.apply(feat, idx, cnt)
  File "/usr/local/lib/python3.6/dist-packages/torchsparse/nn/functional/voxelize.py", line 11, in forward
    out = torchsparse_cuda.insertion_forward(feat.float().contiguous(),
AttributeError: module 'torchsparse_cuda' has no attribute 'insertion_forward'
```
How do I solve this?
I want to get a voxel of dim: #BxCxRxRxR, given that I have a PC of dim: BxNxC.
Any help would be appreciated!

**Comment by Jiayuan-Gu** [comment]
@JohnRomanelis @sinAshish Can you try to use cuda tensor? I encountered the same issue when using CPU tensor. And I found that their spvoxelize only wraps VoxelizeGPU.

**Comment by JohnRomanelis** [comment]
@Jiayuan-Gu Thank you! This seems to fix the problem. I thought that since it doesn't throw an error it wouldn't be a device problem.

**Comment by zhijian-liu** [comment]
Thank you @Jiayuan-Gu !

**Comment by sinAshish** [comment]
> @JohnRomanelis @sinAshish Can you try to use cuda tensor? I encountered the same issue when using CPU tensor. And I found that their spvoxelize only wraps VoxelizeGPU.

Thanks, @Jiayuan-Gu  that works now!
But I want to understand how is it performing 3D convs. I see that the shape is `(N,3)` after voxelization after performing 3D conv it becomes `(N,D)`. But if I want convert it into a cube with `(B,3,R,R,R)`, then what do I do (similar to what is done in PVCNN)? Any help would be appreciated?

**Comment by zhijian-liu** [comment]
It's basically the `to_dense` operation (refer to my answer in https://github.com/mit-han-lab/pvcnn/issues/37).
