### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'rootpath'

### ISSUE THREAD

**Issue by lidonghui-ai** [mit-han-lab/torchsparse#220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have installed TorchSparse v2.1.0 by running the installation script as you suggested:
`python -c "$(curl -fsSL https://raw.githubusercontent.com/mit-han-lab/torchsparse/master/install.py)"`
but when I try the code:
`import torchsparse`
gives

>   File "torchsparse/__init__.pyx", line 6, in init torchsparse.__init__
>   File "torchsparse/utils/tune.pyx", line 15, in init torchsparse.utils.tune
>   File "torchsparse/nn/__init__.pyx", line 2, in init torchsparse.nn.__init__
>   File "torchsparse/nn/modules/__init__.pyx", line 4, in init torchsparse.nn.modules.__init__
>   File "torchsparse/nn/modules/conv.pyx", line 17, in init torchsparse.nn.modules.conv
>   File "torchsparse/nn/functional/__init__.pyx", line 3, in init torchsparse.nn.functional.__init__
>   File "torchsparse/nn/functional/conv/__init__.pyx", line 5, in init torchsparse.nn.functional.conv.__init__
>   File "torchsparse/nn/functional/conv/conv_config.pyx", line 4, in init torchsparse.nn.functional.conv.conv_config
>   File "torchsparse/nn/functional/conv/utils/__init__.pyx", line 2, in init torchsparse.nn.functional.conv.utils.__init__
>   File "torchsparse/nn/functional/conv/utils/private_attribute_dict.pyx", line 6, in init torchsparse.nn.functional.conv.utils.private_attribute_dict
> ModuleNotFoundError: No module named 'rootpath'

Is there anything I missed on the installation??

### Environment

```markdown
- GCC:
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
- NVCC: 
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_Mar__8_18:18:20_PST_2022
Cuda compilation tools, release 11.6, V11.6.124
Build cuda_11.6.r11.6/compiler.31057947_0
- PyTorch: 1.13.0
- PyTorch CUDA: 11.6
- TorchSparse: 2.1.0
```

**Comment by deeptibhegde** [comment]
Hi, how did you solve this issue?

**Comment by lidonghui-ai** [comment]
try pip install rootpath发自我的 iPhone在 2023年7月7日，03:03，Deepti Hegde ***@***.***> 写道：﻿
Hi, how did you solve this issue?

**Comment by lidonghui-ai** [comment]
>
try pip install rootpath
