### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by LYX-SOUL** [mit-han-lab/torchsparse#221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you followed all the steps in the FAQ?

- [X] I have tried the steps in the FAQ.

### Current Behavior

My environment is shown below, the installation is not successful, how to solve it？Thanks！
![torchsparse_error](https://github.com/mit-han-lab/torchsparse/assets/77523024/98bc2747-9008-46de-9068-a9277322c553)

### Error Line

ERROR: torchsparse-21.0+torch110cu111-cp37-cp37-linux X86 64.whl is not a supported wheel on this platform.

### Environment

```markdown
- GCC: 9.4.0
- NVCC: cuda_11.1.TC455_06.29190527_0
- PyTorch: 1.10.0+cu111
- PyTorch CUDA: 11.1
```

### Full Error Log

<details>
  <summary>Error Log</summary>

  [PUT YOUR ERROR LOG HERE]
</details>

**Comment by zhijian-liu** [comment]
@kentang-mit, do we have a pre-built wheel for this environment configuration?

**Comment by zhijian-liu** [comment]
@ys-2020, do we have a pre-built wheel for this environment configuration?

**Comment by ys-2020** [comment]
Yes. We do have a pre-built wheel for this environment. Based on the information above, I think this error shouldn't be caused by the Python/CUDA environment. @LYX-SOUL Would you mind providing more information about your system (e.g., CPU architecture and Linux version)?

Best regards,
Shang

**Comment by LYX-SOUL** [comment]
I use the command "uname -a", the result is: 
Linux b9168767d563 5.4.0-153-generic  x86_64 x86_64 x86_64 GNU/Linux
I use the command "cat /proc/version", the result is: 
Linux version 5.4.0-153-generic (buildd@bos03-amd64-008) (gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1))
@ys-2020 @zhijian-liu

**Comment by douwenhao68** [comment]
@LYX-SOUL 
Try `python -m pip debug --verbose to check the supported tags.  `
Maybe renaming the .whl file 'cp37-cp37' to 'cp37-cp37m' works.
@ys-2020 
However, it shows that the version is 1.4 under the wheel file 'torchsparse-2.1.0+torch112cu113-cp37-cp37m-linux_x86_64.whl', please let me know if I'm wrong.

**Comment by LYX-SOUL** [comment]
Renaming the .whl file 'cp37-cp37' to 'cp37-cp37m' can solve the problem, Thanks！

**Comment by ys-2020** [comment]
Hi @douwenhao68! Thanks for pointing that out. I think renaming the .whl file to 'cp37-cp37m' will work. Actually we are now updating the wheel files on our pypi server to solve the problem.

As to the `torchsparse-2.1.0+torch112cu113-cp37-cp37m-linux_x86_64.whl`, I think the version under this wheel is 2.1.0 from my side. Could you provide more information about how did you get the wheel?

**Comment by ys-2020** [comment]
> Renaming the .whl file 'cp37-cp37' to 'cp37-cp37m' can solve the problem, Thanks！

Glad to hear that!

**Comment by douwenhao68** [comment]
> Hi @douwenhao68! Thanks for pointing that out. I think renaming the .whl file to 'cp37-cp37m' will work. Actually we are now updating the wheel files on our pypi server to solve the problem.
> 
> As to the `torchsparse-2.1.0+torch112cu113-cp37-cp37m-linux_x86_64.whl`, I think the version under this wheel is 2.1.0 from my side. Could you provide more information about how did you get the wheel?

I got the .whl file '[torchsparse-2.1.0+torch112cu113-cp37-cp37-linux_x86_64.whl' from the http://pypi.hanlab.ai/simple/torchsparse/ , then add the 'cp37m' to it.  
Maybe I should wait for the pypi serve to update.

**Comment by ys-2020** [comment]
> > Hi @douwenhao68! Thanks for pointing that out. I think renaming the .whl file to 'cp37-cp37m' will work. Actually we are now updating the wheel files on our pypi server to solve the problem.
> > As to the `torchsparse-2.1.0+torch112cu113-cp37-cp37m-linux_x86_64.whl`, I think the version under this wheel is 2.1.0 from my side. Could you provide more information about how did you get the wheel?
> 
> I got the .whl file '[torchsparse-2.1.0+torch112cu113-cp37-cp37-linux_x86_64.whl' from the http://pypi.hanlab.ai/simple/torchsparse/ , then add the 'cp37m' to it. Maybe I should wait for the pypi serve to update.

That's weird. This should be the right wheel. I'll keep an eye on this problem when updating the pypi server. 

By the way, how did you read the version number?

**Comment by douwenhao68** [comment]
> > > Hi @douwenhao68! Thanks for pointing that out. I think renaming the .whl file to 'cp37-cp37m' will work. Actually we are now updating the wheel files on our pypi server to solve the problem.
> > > As to the `torchsparse-2.1.0+torch112cu113-cp37-cp37m-linux_x86_64.whl`, I think the version under this wheel is 2.1.0 from my side. Could you provide more information about how did you get the wheel?
> > 
> > 
> > I got the .whl file '[torchsparse-2.1.0+torch112cu113-cp37-cp37-linux_x86_64.whl' from the http://pypi.hanlab.ai/simple/torchsparse/ , then add the 'cp37m' to it. Maybe I should wait for the pypi serve to update.
> 
> That's weird. This should be the right wheel. I'll keep an eye on this problem when updating the pypi server.
> 
> By the way, how did you read the version number?

By printing the  __version__, the other modules are still old.
Please notify me after the update. 栓Q！

**Comment by ys-2020** [comment]
> > > > Hi @douwenhao68! Thanks for pointing that out. I think renaming the .whl file to 'cp37-cp37m' will work. Actually we are now updating the wheel files on our pypi server to solve the problem.
> > > > As to the `torchsparse-2.1.0+torch112cu113-cp37-cp37m-linux_x86_64.whl`, I think the version under this wheel is 2.1.0 from my side. Could you provide more information about how did you get the wheel?
> > > 
> > > 
> > > I got the .whl file '[torchsparse-2.1.0+torch112cu113-cp37-cp37-linux_x86_64.whl' from the http://pypi.hanlab.ai/simple/torchsparse/ , then add the 'cp37m' to it. Maybe I should wait for the pypi serve to update.
> > 
> > 
> > That's weird. This should be the right wheel. I'll keep an eye on this problem when updating the pypi server.
> > By the way, how did you read the version number?
> 
> By printing the `__version__`, the other modules are still old. Please notify me after the update. 栓Q！

Sure! I will inform you when the update is finished. But I still think this problem shouldn't be caused by the wheels.

I also printed the `torchsparse.__version__` under this wheel, and got `2.1.0+torch112cu113`. Maybe you need to check if there is an old version of TorchSparse installed in your environment or if a wrong version.py is included in your import path?

**Comment by douwenhao68** [comment]
Sry, it seems like a fault in my copied env.
