### ISSUE TITLE
Tanh implementation

### ISSUE THREAD

**Issue by ErinTUDelft** [mit-han-lab/torchsparse#222]
Thank you for creating this nice engine! I was wondering if other activation functions -such as tanh- will be added in the future, as right now only ReLU and leaky ReLU seem to be available. 

Kind regards,
Erin

**Comment by zhijian-liu** [comment]
You may follow the implementation at https://github.com/mit-han-lab/torchsparse/blob/master/torchsparse/nn/modules/activation.py to implement other activation functions.
