### ISSUE TITLE
"padding" operation for the model

### ISSUE THREAD

**Issue by christy0621** [mit-han-lab/torchsparse#225]
Hi guys,

I'm new to the field and I'm trying to reimplement [Cylinder3D](https://github.com/xinge008/Cylinder3D/blob/master/network/segmentator_3d_asymm_spconv.py) based on torchsparse package. However, I don't find the operation "padding" based on the supported [function](https://github.com/mit-han-lab/torchsparse/blob/897096a820bf410cbeb9664d3ad3ee1a5dc526f4/torchsparse/nn/functional/conv.py#L140). 

Could I get some help to implement that?  Some snip code would be super helpful.

Thanks in advance.

Cheers

**Comment by zhijian-liu** [comment]
I don't think we have circular padding implemented. You probably need to manually pad the input before sending into our convolution.

**Comment by christy0621** [comment]
Cool, thanks for the reply anyway.
