### ISSUE TITLE
Has v2.1.0 code  released yet?

### ISSUE THREAD

**Issue by DezeZhao** [mit-han-lab/torchsparse#226]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Has v2.1.0 code  released yet?

### Expected Behavior

Has v2.1.0 code  released yet?

### Environment

```markdown
- GCC:
- NVCC:
- PyTorch:
- PyTorch CUDA:
- TorchSparse:
```

### Anything else?

Has v2.1.0 code  released yet?

**Comment by zhijian-liu** [comment]
The source code of TorchSparse 2.1.0 is currently undergoing internal quality checks. Stay tuned. Thanks!
