### ISSUE TITLE
Stride of Conv3d has no effect in z-direction?

### ISSUE THREAD

**Issue by Minzhao1995** [mit-han-lab/torchsparse#227]
Hi there,

I'm currently attempting to use Conv3d to downsample voxels. However, I noticed that the stride parameter only seems to have effect in the x and y directions, and not in the z direction. Is this normal behavior for Conv3d, or is there something else I need to do to make it work in the z direction?

Thanks!

**Comment by zhijian-liu** [comment]
Thanks for reporting this issue! This is not the expected behavior. Could you please share a short code snippet to reproduce the issue you mentioned? Thanks!

**Comment by Minzhao1995** [comment]
> Thanks for reporting this issue! This is not the expected behavior. Could you please share a short code snippet to reproduce the issue you mentioned? Thanks!

Thanks for quickly reply. I found out that I mixed up the order of the xyz coordinates and batch index. 

However, I am confused because I noticed some discrepancies between the latest code (commit 897096a) and the documentation (https://torchsparse-docs.github.io/getting_started/basics.html). Would you be able to clarify this for me?

Thanks!

**Comment by ys-2020** [comment]
Hi @Minzhao1995. Your understanding is correct. The batch index should be the first dimension in coordinates since v2.1.0. For `example.py` in commit [897096a](https://github.com/mit-han-lab/torchsparse/commit/897096a820bf410cbeb9664d3ad3ee1a5dc526f4), I think we have already moved batch index to the first dimension.

**Comment by Minzhao1995** [comment]
> Hi @Minzhao1995. Your understanding is correct. The batch index should be the first dimension in coordinates since v2.1.0. For `example.py` in commit [897096a](https://github.com/mit-han-lab/torchsparse/commit/897096a820bf410cbeb9664d3ad3ee1a5dc526f4), I think we have already moved batch index to the first dimension.

Hi, I am a little confused. The sparse_collate() function in [collate.py](https://github.com/mit-han-lab/torchsparse/blob/897096a820bf410cbeb9664d3ad3ee1a5dc526f4/torchsparse/utils/collate.py#L31) seems to concat batch index to the last dimension。

**Comment by ys-2020** [comment]
I see. That is not the code for v2.1.0. The source code of TorchSparse 2.1.0 is currently undergoing internal quality checks. We have only release the wheels currently. Please stay tuned if you want to read the source code. Thanks :)

**Comment by Minzhao1995** [comment]
> I see. That is not the code for v2.1.0. The source code of TorchSparse 2.1.0 is currently undergoing internal quality checks. We have only release the wheels at this stage. Please stay tuned if you want to read the source code. Thanks :)

OK, I see. Thanks again and looking forward to the release.
