### ISSUE TITLE
AttributeError: 'SparseTensor' object has no attribute 'cmaps'

### ISSUE THREAD

**Issue by 440981** [mit-han-lab/torchsparse#229]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you followed all the steps in the FAQ?

- [X] I have tried the steps in the FAQ.

### Current Behavior

new_tensor = SparseTensor(inserted_feat, inserted_coords, 1)
new_tensor.cmaps.setdefault(new_tensor.stride, new_tensor.coords)

### Error Line

AttributeError: 'SparseTensor' object has no attribute 'cmaps'

### Environment

```markdown
- GCC:gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
- NVCC:V11.6.124
- PyTorch:2.0.1+cu117
- PyTorch CUDA:11.7
```

**Comment by ys-2020** [comment]
Hi @440981 , we moved `cmaps` into `SparseTensor._cache` in TorchSparse 2.0.1. Could you please try `new_tensor._caches.cmaps.setdefault(new_tensor.stride, new_tensor.coords)`?

**Comment by 440981** [comment]
> 你好@440981，我们`cmaps`进入`SparseTensor._cache`了 TorchSparse 2.0.1。你能尝试一下`new_tensor._caches.cmaps.setdefault(new_tensor.stride, new_tensor.coords)`吗？

Can you provide whl installation files for version 1.4.0? Upgrade to 2.0.1 too many apis are not available

**Comment by ys-2020** [comment]
Yes. Please check [this tag](https://github.com/mit-han-lab/torchsparse/tree/v1.4.0) for torchsparse 1.4.0

**Comment by 440981** [comment]
> Yes. Please check [this tag](https://github.com/mit-han-lab/torchsparse/tree/v1.4.0) for torchsparse 1.4.0.

Because I do not have sudo permissions, I keep reporting fatal error: google/dense_hash_map: No such file or directory. I have installed Google Sparse Hash

**Comment by 440981** [comment]
In file included from torchsparse/backend/hashmap/hashmap_cpu.cpp:1:
      torchsparse/backend/hashmap/hashmap_cpu.hpp:8:10: fatal error: google/dense_hash_map: No such file or directory
          8 | #include <google/dense_hash_map>
            |          ^~~~~~~~~~~~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for torchsparse
  Running setup.py clean for torchsparse
Failed to build torchsparse
ERROR: Could not build wheels for torchsparse, which is required to install pyproject.toml-based projects

**Comment by ys-2020** [comment]
FYI. You can install [Google Sparse Hash](https://github.com/sparsehash/sparsehash) without sudo. Please refer to this [link] (https://github.com/sparsehash/sparsehash/blob/master/INSTALL).

**Comment by maxiuw** [comment]
Another solution, also does not require `sudo`: use conda env and install `sparsehash` inside your conda env. I did it and build torchsparse sucessfully 

`mamba install conda-forge::sparsehash`

https://anaconda.org/conda-forge/sparsehash
