### ISSUE TITLE
Conv3d with kernel_size=1 and stride=2 doesn't subsample the input tensor

### ISSUE THREAD

**Issue by cslxiao** [mit-han-lab/torchsparse#23]
I found that Conv3d with kernel_size=1 and stride=2 doesn't subsample the input tensor. However, kernel_size=2 and stride=2 do subsample the input tensor.

**Comment by zhijian-liu** [comment]
Thanks for reporting this. It's indeed a bug, and we are working on a fix for this. For now, I think we can stick to k2s2 if you want to downsample the input tensor.

**Comment by Kausta** [comment]
Hello,
I am also having problems with kernel_size=1 / stride=2 convolutions, and wanted to ask whether I should open a new issue ? I know that there has been a PR related to fixing this, but I think there are still some issues. 

The issue I am currently having is with the:
``` 
spnn.Conv3d(
	16, 
	16, 
	kernel_size=1,
	stride=2, 
	bias=False)
```
This normally gives the following error 
```
File "/opt/conda/envs/a/lib/python3.8/site-packages/torchsparse/nn/functional/conv.py", line 51, in forward
    torchsparse.backend.convolution_forward_cuda(
RuntimeError: mat2 must be a matrix
```
and when I run the same code with `CUDA_LAUNCH_BLOCKING=1`, it tries to allocate a 100+-20GB of GPU memory. Kernel Size 2, Stride 2 works perfectly in contrast, and memory usage is reasonable. I am happy to continue with k2s2 configuration, however, this makes it really hard for me to compare model performance with the previous MinkowskiEngine based model I was using. 

I am using the master branch, not the 1.4.0 release. The environment I am using is 
```
- GCC: 8.3.0
- NVCC: 11.3
- PyTorch: 1.12.1+cu113
- PyTorch CUDA: 11.3
```
with an A100 GPU.
Is there any way to make Kernel Size 1 Stride 2 work, or do I have to use Kernel Size 2 Stride 2 ?
If this is not the appropriate place, I can open a new issue. I am also happy to share additional details if necessary.
Thanks
