### ISSUE TITLE
F.sphashquery() shows bug in cpu mode

### ISSUE THREAD

**Issue by Shadow581** [mit-han-lab/torchsparse#231]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![1](https://github.com/mit-han-lab/torchsparse/assets/45356169/4bf0bbd8-0a4b-43a0-a1b5-ac54db8bc862)
<br />
![2](https://github.com/mit-han-lab/torchsparse/assets/45356169/bc6ec8c1-2fdd-4776-8d05-aea0e58c3c19)

Above the two codes, I take variable on cpu to F.sphashquery(), it shows bug. However, I take variable on gpu to F.sphashquery(), it is good.

Could you help me to solve the problem?

My torchsparse Library is `torchsparse-2.1.0+torch112cu113-cp39-cp39-linux_x86_64`.

### Expected Behavior

fix it

### Environment

```markdown
- GCC: 9.4.0
- PyTorch: 1.12.1
- PyTorch CUDA: 11.3
- TorchSparse: 2.1.0+torch112cu113
```

### Anything else?

None

**Comment by zhijian-liu** [comment]
@ys-2020, could you take a look at this issue?

**Comment by Shadow581** [comment]
Nobody answer？

**Comment by ys-2020** [comment]
Hi @Shadow581. Sorry for the late reply. We have temporarily deprecated the cpu version of sphashquery() before. And we are currently working on this problem.

**Comment by Shadow581** [comment]
@ys-2020  ok，thanks

**Comment by ys-2020** [comment]
Hi @Shadow581 , we have solved this problem and update the wheels in our pypi sever. Could you please reinstall torchsparse v2.1.0 with `python -c "$(curl -fsSL https://raw.githubusercontent.com/mit-han-lab/torchsparse/master/install.py)"`? Thank you again for bringing this issue to our attention.
