### ISSUE TITLE
What does Con3d(transposed=True) mean?

### ISSUE THREAD

**Issue by Haerxu** [mit-han-lab/torchsparse#232]
Hi,

I am new to torchsparse. I have a question about the use of Conv3d. In the document, it says
"transposed – If True, use transposed convolution. Default: False."

What does transposed convolution mean? Does it mean upsampling?

**Comment by ys-2020** [comment]
Hi, @Haerxu! Thanks for being interested in TorchSparse. I think your understanding is correct. Transposed convolution means upsampling.

**Comment by Haerxu** [comment]
Thanks
