### ISSUE TITLE
Release of Code for 2.1. version?

### ISSUE THREAD

**Issue by AndreWurl** [mit-han-lab/torchsparse#236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi,

thanks for sharing this awesome library. I have seen multiple sources referring to a version 2.1 of this library, with additions we would really like to use:
Changelog: https://torchsparse-docs.github.io/getting_started/changes.html
"Generative"-Feature: https://github.com/mit-han-lab/torchsparse/issues/215

Seems like the version on pypi is already 2.1., but the code published is 2.0. There already exists a tag with 2.1. but this does not contain the changes described. Unfortunately we cannot use 2.1. without the source code, since we have to make some changes to make this library work in our context.

Can you please provide the source code for 2.1. ?
Even a preliminary (beta) version would be really helpful.

**Comment by zhijian-liu** [comment]
Thanks for letting us know! We are currently working on the code release. Stay tuned!

**Comment by AndreWurl** [comment]
Awesome, thanks for letting us know.

Can you give a rough timeline, or better yet, release a preliminary version? 
We are dependent on the code and have some deadlines coming up. So depending on if the release takes a week, a month, or even longer we might have to switch to a different solution or try to re-implement your changes.

If you can already share a beta version we could use it and can contribute with any fixes / improvement we find. 
This would really help us out.

Thanks for sharing your work openly, we really appreciate it :+1:
