### ISSUE TITLE
[ImportError: cannot import name 'PointTensor' from 'torchsparse'] <title>

### ISSUE THREAD

**Issue by zlynpu** [mit-han-lab/torchsparse#241]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you followed all the steps in the FAQ?

- [X] I have tried the steps in the FAQ.

### Error Line

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'PointTensor' from 'torchsparse' (/home/huile/miniconda3/envs/sparse/lib/python3.8/site-packages/torchsparse/__init__.cpython-38-x86_64-linux-gnu.so)

### Environment

```markdown
- GCC:11.4.0
- NVCC:11.7
- PyTorch:1.13.0
- PyTorch CUDA:11.7
```

### Full Error Log

<details>
  <summary>Error Log</summary>

  [PUT YOUR ERROR LOG HERE]
</details>

**Comment by zlynpu** [comment]
I downloaded the .whl file for installation from http://pypi.hanlab.ai/simple/torchsparse/.

**Comment by Amber0913** [comment]
Do you solve this problem?

**Comment by wbjsamuel** [comment]
Same issue. How did you solve that?
