### ISSUE TITLE
[BUG] <title>File "torchsparse/nn/functional/conv/func/implicit_gemm.pyx", line 160, in torchsparse.nn.functional.conv.func.implicit_gemm.ImplicitGEMMConvolutionFuntion.backward RuntimeError: shape '[27, 32, 4]' is invalid for input of size 5184

### ISSUE THREAD

**Issue by lihc-cz** [mit-han-lab/torchsparse#243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

File "torchsparse/nn/functional/conv/func/implicit_gemm.pyx", line 160, in torchsparse.nn.functional.conv.func.implicit_gemm.ImplicitGEMMConvolutionFuntion.backward
RuntimeError: shape '[27, 32, 4]' is invalid for input of size 5184

### Environment

```markdown
- GCC:
- NVCC:
- PyTorch:
- PyTorch CUDA:
- TorchSparse:
```

**Comment by ys-2020** [comment]
Hi @lihc-cz , could you please provide more details about the error (e.g., a sample code snippet that we could reproduce this bug)? From the information provided, it seems that your (kernel_volume, oc, ic) doesn't match the shape of output weight_gradient.
