### ISSUE TITLE
Error: cannot import name 'PointTensor' from 'torchsparse'

### ISSUE THREAD

**Issue by Amber0913** [mit-han-lab/torchsparse#248]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Could you provide the wheels of v2.0.0？I encountered an installation error when using this statement pip install --upgrade git+https://github.com/mit-han-lab/torchsparse.git@v2.0.0.

### Environment

```markdown
- GCC:
- NVCC:
- PyTorch:
- PyTorch CUDA:
- TorchSparse:
```

**Comment by zhijian-liu** [comment]
We don't have pre-built wheels from v2.0.0. Could you provide the detailed installation error?

**Comment by binaryannamolly** [comment]
I have the same error.
Error: cannot import name 'PointTensor' from 'torchsparse' 

ImportError: cannot import name 'PointTensor' from 'torchsparse' (.../python3.10/site-packages/torchsparse/__init__.cpython-310-x86_64-linux-gnu.so)

My environment,

Ubuntu 22.04.2 LTS
PyCharm 2023.2.3 (Professional Edition)
Python 3.10
torch version 2.0.1+cu118
cuda version 11.8

Torchparse was installed using,
python -c "$(curl -fsSL https://raw.githubusercontent.com/mit-han-lab/torchsparse/master/install.py)"

**Comment by DJNing** [comment]
Same issue here

**Comment by binaryannamolly** [comment]
@DJNing this worked for me, pip install --upgrade git+https://github.com/mit-han-lab/torchsparse.git@v1.4.0.

**Comment by liyuan-qiu** [comment]
same issue, where can I download the torchsparse 1.4.0
