### ISSUE TITLE
[BUG] Only support subm mode?

### ISSUE THREAD

**Issue by matri123** [mit-han-lab/torchsparse#249]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

In rule_book generation process, only has subm mode's rule_book. so, it doesn't have normal mode?
And in spconv process, only subm rule_book can be used? or, normal rule_book also works?

### Environment

```markdown
- GCC:
- NVCC:
- PyTorch:
- PyTorch CUDA:
- TorchSparse:
```

**Comment by zhijian-liu** [comment]
@ys-2020, could you please take a look at this issue when you have time? Thanks!

**Comment by ys-2020** [comment]
Hi @matri123 , a normal convolution mode is supported in our framework. Could you further clarify which part makes you confused? Maybe with a link to the doc or a sample code. Thanks

**Comment by matri123** [comment]
https://github.com/mit-han-lab/torchsparse/blob/master/torchsparse/nn/functional/build_kmap.py#L32
only has subm and downsample, does

**Comment by ys-2020** [comment]
Hi. In subm mode, the input feature map will not be downsampled. (The output resolution and point coordinates will be kept the same as input.) I guess this might be the normal mode you want?

**Comment by ys-2020** [comment]
Close this issue as complete. If you have further questions, feel free to reopen it.
