### ISSUE TITLE
[BUG] <title>Don't know the details about the function "SparseTensor.dense()"

### ISSUE THREAD

**Issue by nancyhxn** [mit-han-lab/torchsparse#251]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The latest version 2.1.0 was just updated in October to add a SparseTensor.dense() method. Currently, the author just says he added this, but the documentation has not been updated with the introduction, and GitHub is stuck at version 2.0.0b with no introduction. This prevents me from using this method better.

### Expected Behavior

Can you tell me what the path to this file “SparseTensor.dense() ” is, so I can understand how this function is written, or can you just answer me this question?

**Comment by zhijian-liu** [comment]
@ys-2020, could you reflect this change in our documentation? Thanks!

**Comment by nancyhxn** [comment]
Thank you so much for the update!

**Comment by ys-2020** [comment]
Closed it as completed. If you have further questions, please feel free to reach out.
