### ISSUE TITLE
How to provide asymmetrical kernels in torchsparse.nn.Conv3d

### ISSUE THREAD

**Issue by sandeepnmenon** [mit-han-lab/torchsparse#26]
On checking the code for the Conv3d feature
https://github.com/mit-han-lab/torchsparse/blob/cc3d5b15070ba88e912ebd65dfa21b01a826ec98/torchsparse/nn/modules/conv.py#L17
I see that the kernel size is an integer. 
Is it possible to give asymmetric kernels. eg of shape=3×1×3, 1×3×3 etc
From latest [literature](https://arxiv.org/pdf/2008.01550.pdf), I see that 

> asymmetric kernels significantly reduces the computational cost of conventional 3D convolutional kernels. Specifically,
> using a convolution with kernel=3×1×3 followed by a 1×3×3 convolution is equivalent to sliding
> a two layer network with the same receptive field as in a 3D convolution with kernel= 3 × 3 × 3, but
> it has 33% cheaper computational cost than a 3 × 3 × 3 convolution with same number of output
> filters.

Also, it has some other properties that I wanted to explore.
I am using the torchsparse library to build my model and did not see the option to give a tuple as the kernel size like in this [example](https://github.com/xinge008/Cylinder3D/blob/0fdba5e7f9a0a396458e86d945cc5c6c92df31d6/network/segmentator_3d_asymm_spconv.py#L17) of the library spconv.
Is this functionality supported? If not, is it in your roadmap?

Thank you

**Comment by sandeepnmenon** [comment]
I would like to contribute the addition of asymmetric kernels.

**Comment by zhijian-liu** [comment]
Thank you! That would be great. Feel free to add me as a reviewer after you have the PR.

**Comment by sandeepnmenon** [comment]
Raised PR #28 
@zhijian-liu Please review
