### ISSUE TITLE
[BUG] AttributeError: module 'torchsparse.nn.functional' has no attribute 'get_default_conv_config'

### ISSUE THREAD

**Issue by Tortoise0Knight** [mit-han-lab/torchsparse#262]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm running `python examples/example.py`, and the error occured:

Traceback (most recent call last):
  File "/workspace/mwx/torchsparse/examples/example.py", line 45, in <module>
    conv_config = F.get_default_conv_config()
AttributeError: module 'torchsparse.nn.functional' has no attribute 'get_default_conv_config'

### Expected Behavior

Should it be F.conv_config.get_default_conv_config() ?

### Environment

```markdown
- GCC: 7.5.0
- NVCC: V11.1.105
- PyTorch: 1.10.0+cu111
- PyTorch CUDA: 11.1
- TorchSparse: 2.1.0
```

**Comment by ys-2020** [comment]
Yes. `F.conv_config.get_default_conv_config()` should be correct. Thanks for pointing that out!
