### ISSUE TITLE
May I ask if spnn.conv3d is a submanifold sparse convolution or a regular sparse convolution?

### ISSUE THREAD

**Issue by Shixiaomeng7** [mit-han-lab/torchsparse#265]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

May I ask if spnn. conv3d in torch sparse is a submanifold sparse convolution or a regular sparse convolution? How to distinguish like spconv.SubMConv3d and spconv.SparseConv3d in spconv?

### Environment

```markdown
- GCC:
- NVCC:
- PyTorch:
- PyTorch CUDA:
- TorchSparse:
```

**Comment by ys-2020** [comment]
We support both submanifold and regular sparse convolution in `spnn.conv3d`. Just change the stride parameter to run the two types of convolution.
