### ISSUE TITLE
[Installation] installing Google's sparse hashmap without root

### ISSUE THREAD

**Issue by hdacnw** [mit-han-lab/torchsparse#271]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you followed all the steps in the FAQ?

- [X] I have tried the steps in the FAQ.

### Current Behavior

I've installed sparse hashmap in ~/.local/lib following https://github.com/mit-han-lab/torchsparse/issues/15 How do I reference it?

### Error Line

No such file or directory #include <sparsehash/internal/sparseconfig.h>

### Environment

```markdown
- GCC:
- NVCC:
- PyTorch:
- PyTorch CUDA:
```

### Full Error Log

<details>
  <summary>Error Log</summary>

  [PUT YOUR ERROR LOG HERE]
</details>

**Comment by ys-2020** [comment]
Hi @hdacnw, please refer to this file for the installation of Google Sparse Hash. https://github.com/sparsehash/sparsehash/blob/master/INSTALL

**Comment by ioeddk** [comment]
If you want to simply install google-sparsehash to build your Torchsparse in developer mode, you can install sparsehash with conda. Please refer to [here](https://anaconda.org/bioconda/google-sparsehash).
