### ISSUE TITLE
[BUG] what 2.0.0b0 diffrence about 2.1.0? use 2.1.0 and SparseResUNet42, at foward encode at last layer, coord.shape is [0,4],but use 2.0.0.b0，it is ok.

### ISSUE THREAD

**Issue by yeyan00** [mit-han-lab/torchsparse#273]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

use 2.1.0 and SparseResUNet42 as backbone, same data，after encoder last layer of at foward downsample , the coord.shape is [0,4], but switch 2.0.0.b0，nothing modifed，it work well. 
for pypi server is blocked, i install 2.1.0 from source code by use 
```
python -m pip install -e .
```
when use 2.1.0，i set coordinate order is  [batch, x, y, z]，when use 2.0.0b0，the order is[x, y, z, batch]
is there other parameters should i set?
```
unet.py-->_unet_forward
# len(encoders)=1
# downsample
xd = encoders[0](x)


# set coords order 
 if ts_version>='2.1.0':
          x.coords =  torch.cat((batch.reshape(-1,1),x.coords), dim=1).int()
      else:
          # version<=2.0.0
          x.coords =  torch.cat((x.coords, batch.reshape(-1,1)), dim=1).int()

```

### Environment

```markdown
- GCC:9.4.0
- NVCC:11.6
- PyTorch:1.13
- PyTorch CUDA:11.6
- TorchSparse:2.1.0
```

**Comment by zhijian-liu** [comment]
We just fixed our PyPI server. Could you please try installing TorchSparse with PyPI?

**Comment by ys-2020** [comment]
Hi @yeyan00 , could you please provide a runnable snippet code for us to reproduce the error if it still exists?

**Comment by yeyan00** [comment]
> Hi @yeyan00 , could you please provide a runnable snippet code for us to reproduce the error if it still exists?

ok,i will install use pypi server first, if it still has this error, i will provide runnable code

**Comment by yeyan00** [comment]
> We have just fixed our PyPI server. Could you please try installing TorchSparse with PyPI? Thanks!

i install it from download whl file，train 3 epoch, it seems ok. 
is there any difference between compiled version and  source code?

i install from latest source code like this:
```
export CUDA_HOME=/home/szlt/anaconda3/envs/torch_113     
python -m pip install -e .
```

**Comment by ys-2020** [comment]
I think there is no major difference between the pre-compiled version and the source code. Please feel free to use the pre-compiled version if you cannot build it from source successfully.

**Comment by ys-2020** [comment]
Close this issue as completed. Feel free to reopen it if you have any further questions.
