### ISSUE TITLE
[Installation] Hanlab Website with Wheels Down

### ISSUE THREAD

**Issue by fishbotics** [mit-han-lab/torchsparse#275]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you followed all the steps in the FAQ?

- [X] I have tried the steps in the FAQ.

### Current Behavior

Hanlab website is broken. This link leads to a cloudflare issue: http://pypi.hanlab.ai/simple/torchsparse

This also is leading the installation script to fail

### Error Line

There is no error because I am unable to even pull from the server

### Environment

```markdown
- GCC:
- NVCC:
- PyTorch:
- PyTorch CUDA:
```

### Full Error Log

<details>
  <summary>Error Log</summary>

  [PUT YOUR ERROR LOG HERE]
</details>

**Comment by zhijian-liu** [comment]
We have fixed our PyPI server. Could you please try it again? Thanks!

**Comment by ErenBalatkan** [comment]
It gives following error;

502 Bad Gateway
nginx/1.18.0 (Ubuntu)

**Comment by ys-2020** [comment]
Hi @ErenBalatkan , could you please try this link instead?

http://24.199.104.228/simple

**Comment by ErenBalatkan** [comment]
I can access the website on this link; http://24.199.104.228/simple
I can also access this; http://24.199.104.228/simple/torchsparse/

Original pypy link gives following error now;
```
Application Blocked
Access to the application you were trying to use has been blocked in accordance with company policy. Please contact your system administrator if you believe this is in error.

User: ***.*** (my ip)

Application: web-browsing
```

**Comment by ys-2020** [comment]
I see. Thank you for letting us know!

**Comment by bian-hengwei** [comment]
http://24.199.104.228/simple is also broken. Is there an alternative way for downloading the wheels? Thank you!
