### ISSUE TITLE
Any plan to support bfloat16?

### ISSUE THREAD

**Issue by pycoco** [mit-han-lab/torchsparse#276]

**Comment by zhijian-liu** [comment]
@ys-2020, could you please take a look at this issue when you have time? Thanks!

**Comment by pycoco** [comment]
@ys-2020 Thanks for your quick reply and great work，i found that model with float16 will encounter loss nan problem in certain scenarios. Maybe it is caused by underflow/overflow. So this a good choice to support bfloat16 in training.

**Comment by ys-2020** [comment]
@pycoco . Hi! Thank you for the feedback. Can you provide more details about the 'certain scenario'? Actually we have launched a lot of training jobs on segmentation/detection tasks and many different datasets, and we didn't meet the nan loss. (Also, you can change to fp32 as a backup plan.)

**Comment by pycoco** [comment]
@ys-2020 In my scenario, i use voxel size `[0.05, 0.05, 0.15]`, range `[-100.0, -100.0, -1.5, 100.0, 100.0, 4.5]` and own dataset. FP32 is normal but training time is too long. Actually i use 'spconv' now, maybe i should adapt to our library and have a try(but i think the library is not the reason of the problem).
