### ISSUE TITLE
关于sparse的计算量

### ISSUE THREAD

**Issue by nancyhxn** [mit-han-lab/torchsparse#277]
请问将sparse运用在自己的算法中，该如何计算sparse所占用的计算量？我目前的发现是直接调用“from thop import profile”的profile函数，不能计算到sparse的计算量，会被直接忽略掉。
请问这个问题该如何解决？

**Comment by zhijian-liu** [comment]
Yes, you need to write a customized hook for sparse convolution.

**Comment by ys-2020** [comment]
Hi @nancyhxn , I think the [kmap](https://github.com/mit-han-lab/torchsparse/blob/master/torchsparse/nn/functional/conv/conv.py#L76) for sparse convolution might be helpful. You can refer to the [out_in_map](https://github.com/mit-han-lab/torchsparse/blob/master/torchsparse/nn/functional/conv/func/implicit_gemm.py#L28) to calculate the theoretically minimal flops for sparse convolution. You may also need the [reduced_mask](https://github.com/mit-han-lab/torchsparse/blob/master/torchsparse/nn/functional/conv/func/implicit_gemm.py#L30C13-L30C32) to compute the actual macs in TorchSparse v2.1.0. Please refer to our [paper](https://www.dropbox.com/scl/fi/obdku0kqxjlkvuom2opk4/paper.pdf?rlkey=0zmy8eq9fzllgkx54zsvwsecf&dl=0) for more details.

**Comment by ys-2020** [comment]
Close this issue due to inactivity. Please feel free to reopen it if you have any further questions.
