### ISSUE TITLE
Differences between branch master and v2.1.0

### ISSUE THREAD

**Issue by getianao** [mit-han-lab/torchsparse#289]
Thank you for your excellent work.

I'm currently working on aligning the performance of the TorchSparse library with the MICRO'23 paper. However, I've noticed that both branches (master and v2.1.0) incorporate the techniques mentioned in the paper. I wrote a code snippet that works for v2.1.0, but unfortunately, it doesn't seem to work for the master branch.

Could you please clarify the differences between these two branches? Are there any updates in the master branch that are not covered in the MICRO'23 paper?

**Comment by ys-2020** [comment]
Hi @getianao , thank you for your interest in TorchSparse! There shouldn't be major difference between the master branch and the v2.1.0 branch. Could you please provide the error message you met when using the master branch? Thank you.
