### ISSUE TITLE
[Installation] Error: cannot import name 'PointTensor' from 'torchsparse'

### ISSUE THREAD

**Issue by binaryannamolly** [mit-han-lab/torchsparse#291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you followed all the steps in the FAQ?

- [X] I have tried the steps in the FAQ.

### Current Behavior

I have the same error.
Error: cannot import name 'PointTensor' from 'torchsparse'

ImportError: cannot import name 'PointTensor' from 'torchsparse' (.../python3.10/site-packages/torchsparse/init.cpython-310-x86_64-linux-gnu.so)

My environment,

Ubuntu 22.04.2 LTS
PyCharm 2023.2.3 (Professional Edition)
Python 3.10
torch version 2.0.1+cu118
cuda version 11.8

Torchparse was installed using,
python -c "$(curl -fsSL https://raw.githubusercontent.com/mit-han-lab/torchsparse/master/install.py)"

### Error Line

/spvnas/core/models/semantic_kitti/spvnas.py", line 9, in <module>
    from torchsparse import PointTensor, SparseTensor

### Environment

```markdown
- GCC: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
- NVCC: Build cuda_11.8.r11.8/compiler.31833905_0
- PyTorch: 2.0.1
- PyTorch CUDA: cu118
```

### Full Error Log

<details>
  <summary>Error Log</summary>

Traceback (most recent call last):
  File "/spvnas/test_spvnas108m_cluster.py", line 178, in <module>
    main()
  File "/spvnas/test_spvnas108m_cluster.py", line 74, in main
    from core.models.semantic_kitti.spvnas_cluster import SPVNAS
  File "/spvnas/core/models/semantic_kitti/__init__.py", line 1, in <module>
    from .spvnas import *
  File "/spvnas/core/models/semantic_kitti/spvnas.py", line 9, in <module>
    from torchsparse import PointTensor, SparseTensor
ImportError: cannot import name 'PointTensor' from 'torchsparse' (.../python3.10/site-packages/torchsparse/__init__.cpython-310-x86_64-linux-gnu.so)
</details>

**Comment by meisa233** [comment]
Same here

**Comment by binaryannamolly** [comment]
Thanks! This seems to work as well.
pip install --upgrade git+https://github.com/mit-han-lab/torchsparse.git@v1.4.0

**Comment by Shuhul24** [comment]
This is the error I am ending up with following both the methods mentioned above:
```python
Collecting git+https://github.com/mit-han-lab/torchsparse.git@v1.4.0
  Cloning https://github.com/mit-han-lab/torchsparse.git (to revision v1.4.0) to /tmp/pip-req-build-2n7akl7f
  Running command git clone --filter=blob:none --quiet https://github.com/mit-han-lab/torchsparse.git /tmp/pip-req-build-2n7akl7f
  fatal: unable to access 'https://github.com/mit-han-lab/torchsparse.git/': Failed to connect to github.com port 443: Connection timed out
  error: subprocess-exited-with-error
  
  × git clone --filter=blob:none --quiet https://github.com/mit-han-lab/torchsparse.git /tmp/pip-req-build-2n7akl7f did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/mit-han-lab/torchsparse.git /tmp/pip-req-build-2n7akl7f did not run successfully.
│ exit code: 128
╰─> See above for output.
```
My specs are: 
```
Python: 3.10.18
PyTorch: 2.0.0+cu118
CUDA: 11.8
GCC: 11.4
```

How to avoid this error? Are there any different approaches? I tried installing twice with `torch.cuda.is_available()` as `True` and `False` both.
