### ISSUE TITLE
SparseResUNet42 should have LAYERS = (2, 3, 4, 6, 2, 2, 2, 2) instead of LAYERS = (2, 2, 2, 2, 2, 2, 2, 2)

### ISSUE THREAD

**Issue by YilmazKadir** [mit-han-lab/torchsparse#301]
From my understanding, in the original Spatiotemporal Segmentation paper MinkowskiNet42 (Res16UNet34C) has LAYERS = (2, 3, 4, 6, 2, 2, 2, 2). However, your SparseResUNet42 implementation has LAYERS = (2, 2, 2, 2, 2, 2, 2, 2). Is there a mistake in the naming or am I missing a detail?

**Comment by zhijian-liu** [comment]
Our implementation serves as a reference point. We didn't adhere to the exact settings of MinkowskiNet.
