### ISSUE TITLE
torchsparse_cuda issue

### ISSUE THREAD

**Issue by RS-Coop** [mit-han-lab/torchsparse#31]
Hello, I am having the following issue with torchsparse which arises when torchsparse_cuda calls hash_forward():

```
AttributeError: module 'torchsparse_cuda' has no attribute 'hash_forward'
```

I believe the root of the problem is due to the process of torchsparse installation. On my machine I do not have CUDA installed system-wide. Instead I use conda virtual environments and install cudatoolkit and cudnn as required. In the torchsparse setup.py it is checking for CUDA_HOME != None which I think eventually causes the problem.

Altogether I suppose my question/issue is that I would like to use torchsparse without having to change my exisiting CUDA installation process. Is this possible?

**Comment by zhijian-liu** [comment]
Could you check the device of your tensor: `tensor.device.type`? I guess it's `CUDA` right?

**Comment by RS-Coop** [comment]
Yes that is correct.

**Comment by zhijian-liu** [comment]
I see. I think in this case, it would be better to use the CPU implementation (by `.cpu()`).

**Comment by RS-Coop** [comment]
Can I ask as to why? It seems that my setup is pretty common, or perhaps I am wrong and it is better to install CUDA system-wide? Or does it come down to torchsparse implementation details?

**Comment by zhijian-liu** [comment]
I think I might misunderstand your case. If I understand correctly now, you have a CUDA installed locally but not system-wide. In this case, you might need to reinstall `torchsparse` with `FORCE_CUDA=1`.

**Comment by sandeepnmenon** [comment]
Reinstalling torchsparse with
```
FORCE_CUDA="1"
TORCH_CUDA_ARCH_LIST="${TORCH_CUDA_ARCH_LIST}"
```
replace ${TORCH_CUDA_ARCH_LIST} with the GPU architecture of your machine.

I faced similar issue https://github.com/mit-han-lab/e3d/issues/23

**Comment by RS-Coop** [comment]
@zhijian-liu Yes that is correct, I only have CUDA installed through an Anaconda virtual environment.

If I do the following before trying to install torchsparse:
```
$ export FORCE_CUDA="1"
```
I get an error saying CUDA_HOME is not set. Also note that without setting this variable torchsparse installs fine, things just break when I try to run something.

If I add the following:
```
$ export CUDA_HOME="None"
```
I get even more errors related to CUDA and building torchsparse.

@sandeepnmenon I am not entirely sure what you mean by the GPU architecture of my machine. Is this just the type of GPU card I have? In looking at your linked issue I was still not sure, and in my case I am not using Docker.

**Comment by zhijian-liu** [comment]
That's normal. Without setting `FORCE_CUDA`, the library will only install the CPU kernels as we cannot find `CUDA_HOME`. Could you double-check the location of your `CUDA_HOME`? I guess it might be in Anaconda.

**Comment by zhijian-liu** [comment]
No worries at all. We would love to help you with this. From https://stackoverflow.com/questions/52298146/cuda-home-in-pytorch-installation, it seems that the CUDA installation in Anaconda is not a complete one, which might cause the issue. I guess an easier way is to install the full CUDA from NVIDIA: https://developer.nvidia.com/cuda-10.2-download-archive. It can be installed without root permission actually.

**Comment by RS-Coop** [comment]
I agree that doing the full CUDA install is easier, and I have root permission so that is not a problem. Mostly I was just looking for a way to fix things using my current workflow, but I realize that may not be possible/easy.

**Comment by RS-Coop** [comment]
That seems to have fixed my problems (as expected). Thanks for all the help!
