### ISSUE TITLE
[Installation] Please tag the 2.1.0 code

### ISSUE THREAD

**Issue by gspr** [mit-han-lab/torchsparse#311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you followed all the steps in the FAQ?

- [X] I have tried the steps in the FAQ.

### Current Behavior

Documentation consistently refers to version 2.1.0, and prebuilt wheels for that version are provided. However, there's no corresponding git tag, so it's very hard to know what source code constitutes version 2.1.0. This is bad for reproducibility. Please consider tagging all versioned releases.

### Error Line

```
$ git tag | grep v2.0.0 | wc -l 
1
$ git tag | grep v2.1.0 | wc -l 
0
```

### Environment

```markdown
N/A
```

**Comment by zhijian-liu** [comment]
Please use the main branch as v2.1.0

**Comment by gspr** [comment]
On 31 July 2024 17:18:31 CEST, Zhijian Liu ***@***.***> wrote:
>Please use the main branch as v2.1.0
>

Thanks for getting back to me.

I'm sorry, but I don't think I understand your suggestion. Any branch with multiple commits – such as obviously master/main, but also the v2.1.0 branch – is unsuitable as a representation of a versioned release. 

Which *commit* on the suggested branch reflects version 2.1.0?
