### ISSUE TITLE
[Installation] <title>No version for installation

### ISSUE THREAD

**Issue by zhanxch** [mit-han-lab/torchsparse#313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you followed all the steps in the FAQ?

- [X] I have tried the steps in the FAQ.

### Current Behavior

Could not find a version that satisfies the requirement torchsparse==2.1.0+torch20cu117 (from versions: none). 

For command `python -c "$(curl -fsSL https://raw.githubusercontent.com/mit-han-lab/torchsparse/master/install.py)"`; The website mentioned in README is also inaccessible.

### Error Line

he detected CUDA version (12.4) mismatches the version that was used to compile
      PyTorch (11.7). Please make sure to use the same CUDA versions. How can I install torchsparse for cuda11.7 ?

### Environment

```markdown
- GCC:
- NVCC:
- PyTorch:2.1.0
- PyTorch CUDA:11.7
```

### Full Error Log

      RuntimeError:
      The detected CUDA version (12.4) mismatches the version that was used to compile
      PyTorch (11.7). Please make sure to use the same CUDA versions.
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for torchsparse
  Running setup.py clean for torchsparse
Failed to build torchsparse
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (torchsparse)

**Comment by zhijian-liu** [comment]
Could you try to install TorchSparse from source using
```
pip install git+https://github.com/mit-han-lab/torchsparse.git
```
