### ISSUE TITLE
[BUG] Conv3d: Inconsistent docs on bias=True|False

### ISSUE THREAD

**Issue by francotheengineer** [mit-han-lab/torchsparse#318]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In the docs, it clearly shows that bias=False in the default function typing/defaults:

```
class Conv3d(..., bias: [bool](https://docs.python.org/3/library/functions.html#bool) = False, ...) = None)
```

The codebase also has bias set to False:

```
class Conv3d(nn.Module):
    def __init__(
        self,
        in_channels: int,
        out_channels: int,
        kernel_size: Union[int, List[int], Tuple[int, ...]] = 3,
        stride: Union[int, List[int], Tuple[int, ...]] = 1,
        padding: Union[int, Tuple[int, ...]] = 0,
        dilation: int = 1,
        bias: bool = False,
        transposed: bool = False,
        generative: bool = False,
        config: Dict = None,
    ) -> None:
```

But the doc string states the inverse:
`bias ([bool](https://docs.python.org/3/library/functions.html#bool)) – If True, add a learnable bias to the output. Default: True.`

This is different from PyTorch
Questions:
1) Am I correct in thinking that bias, by default, is False?  
2) Why is bias not commonly used in sparse conv networks?

### Environment

```markdown
- GCC: N/A
- NVCC: N/A
- PyTorch: N/A
- PyTorch CUDA: N/A
- TorchSparse: N/A
```

**Comment by zhijian-liu** [comment]
Please follow the definition in the code. Thanks!
