### ISSUE TITLE
[Installation] <title>

### ISSUE THREAD

**Issue by JuandZuniga** [mit-han-lab/torchsparse#322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you followed all the steps in the FAQ?

- [X] I have tried the steps in the FAQ.

### Current Behavior

Hi, I'm trying to install this library but I get the following error

### Error Line

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for torchsparse
  Running setup.py clean for torchsparse
Failed to build torchsparse
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (torchsparse)

### Environment

```markdown
- GCC:-
- NVCC:-
- PyTorch:-
- PyTorch CUDA:-
```

### Full Error Log

<details>
  <summary>Error Log</summary>
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for torchsparse
  Running setup.py clean for torchsparse
Failed to build torchsparse
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (torchsparse)
</details>

**Comment by zhijian-liu** [comment]
Could you try to install TorchSparse from source using
```
pip install git+https://github.com/mit-han-lab/torchsparse.git
```
