### ISSUE TITLE
In torch.sparse v2.0. The batch_size should be put in the last dimension or the first dimension ?

### ISSUE THREAD

**Issue by Miaosheng1** [mit-han-lab/torchsparse#324]
Hi, i encounter a question about how to construct the `sparseTensor`. In the v1.4.0, i suppose the batch_size should be put into the in the **last dimension** as in the [SparseNeus code](https://github.com/xxlong0/SparseNeuS/blob/ce3b7ef35e5c737ed2505d8cc54ee22ee0ed6415/models/sparse_sdf_network.py#L358-L364).  where i also notcie the [issue235](https://github.com/mit-han-lab/torchsparse/pull/235) that claim batch_size should be put into the in the **first dimension**. I am really confused about the usage of `SparseTensor`, Can you provide more detailed instruction about how i correctly constrcuts sparseTensor in `TrochSparse v2.0`? Thanks a lot.

**Comment by francotheengineer** [comment]
TorchSparse V2 uses batch first notation `[batch, x, y, z]`. https://torchsparse-docs.github.io/getting_started/changes.html#coordinate-order-batch-first
