### ISSUE TITLE
[Installation] <cannot import name 'PointTensor' from 'torchsparse.tensor' , where can I download the version 1.4.0>

### ISSUE THREAD

**Issue by liyuan-qiu** [mit-han-lab/torchsparse#328]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you followed all the steps in the FAQ?

- [X] I have tried the steps in the FAQ.

### Current Behavior

ImportError: cannot import name 'PointTensor' from 'torchsparse.tensor' (/root/miniconda3/envs/neucon5/lib/python3.8/site-packages/torchsparse-2.1.0-py3.8-linux-x86_64.egg/torchsparse/tensor.py)

### Error Line

(neucon5) root@48611ad9f641:/NeuralRecon# FORCE_CUDA=1 pip install --no-cache-dir git+https://github.com/mit-han-lab/torchsparse.git
Collecting git+https://github.com/mit-han-lab/torchsparse.git
  Cloning https://github.com/mit-han-lab/torchsparse.git to /tmp/pip-req-build-0rt23rka
  Running command git clone --filter=blob:none --quiet https://github.com/mit-han-lab/torchsparse.git /tmp/pip-req-build-0rt23rka
  Resolved https://github.com/mit-han-lab/torchsparse.git to commit 9eb3b88c5f3b6009560990a55c4aca7d62e8af60
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /root/miniconda3/envs/neucon5/lib/python3.8/site-packages (from torchsparse==2.1.0) (1.24.4)
Requirement already satisfied: backports.cached_property in /root/miniconda3/envs/neucon5/lib/python3.8/site-packages/backports.cached_property-1.0.2-py3.8.egg (from torchsparse==2.1.0) (1.0.2)
Requirement already satisfied: tqdm in /root/miniconda3/envs/neucon5/lib/python3.8/site-packages (from torchsparse==2.1.0) (4.66.5)
Requirement already satisfied: typing-extensions in /root/miniconda3/envs/neucon5/lib/python3.8/site-packages (from torchsparse==2.1.0) (4.11.0)
Requirement already satisfied: wheel in /root/miniconda3/envs/neucon5/lib/python3.8/site-packages (from torchsparse==2.1.0) (0.43.0)
Requirement already satisfied: rootpath in /root/miniconda3/envs/neucon5/lib/python3.8/site-packages/rootpath-0.1.1-py3.8.egg (from torchsparse==2.1.0) (0.1.1)
Requirement already satisfied: torch in /root/miniconda3/envs/neucon5/lib/python3.8/site-packages (from torchsparse==2.1.0) (2.0.0+cu118)
Requirement already satisfied: torchvision in /root/miniconda3/envs/neucon5/lib/python3.8/site-packages (from torchsparse==2.1.0) (0.15.0+cu118)
Requirement already satisfied: six>=1.11.0 in /root/miniconda3/envs/neucon5/lib/python3.8/site-packages (from rootpath->torchsparse==2.1.0) (1.16.0)
Requirement already satisfied: coloredlogs>=10.0 in /root/miniconda3/envs/neucon5/lib/python3.8/site-packages/coloredlogs-15.0.1-py3.8.egg (from rootpath->torchsparse==2.1.0) (15.0.1)
Requirement already satisfied: termcolor>=1.1.0 in /root/miniconda3/envs/neucon5/lib/python3.8/site-packages/termcolor-2.4.0-py3.8.egg (from rootpath->torchsparse==2.1.0) (2.4.0)
Requirement already satisfied: colour-runner>=0.0.5 in /root/miniconda3/envs/neucon5/lib/python3.8/site-packages/colour_runner-0.1.1-py3.8.egg (from rootpath->torchsparse==2.1.0) (0.1.1)
Requirement already satisfied: deepdiff>=3.3.0 in /root/miniconda3/envs/neucon5/lib/python3.8/site-packages/deepdiff-8.0.1-py3.8.egg (from rootpath->torchsparse==2.1.0) (8.0.1)
Requirement already satisfied: pygments>=2.2.0 in /root/miniconda3/envs/neucon5/lib/python3.8/site-packages (from rootpath->torchsparse==2.1.0) (2.15.1)
Requirement already satisfied: tox>=3.0.0 in /root/miniconda3/envs/neucon5/lib/python3.8/site-packages/tox-4.18.0-py3.8.egg (from rootpath->torchsparse==2.1.0) (4.18.0)
Requirement already satisfied: coverage>=4.5.2 in /root/miniconda3/envs/neucon5/lib/python3.8/site-packages/coverage-7.6.1-py3.8-linux-x86_64.egg (from rootpath->torchsparse==2.1.0) (7.6.1)
Requirement already satisfied: codecov>=2.0.15 in /root/miniconda3/envs/neucon5/lib/python3.8/site-packages/codecov-2.1.13-py3.8.egg (from rootpath->torchsparse==2.1.0) (2.1.13)
Requirement already satisfied: filelock in /root/miniconda3/envs/neucon5/lib/python3.8/site-packages (from torch->torchsparse==2.1.0) (3.15.4)
Requirement already satisfied: sympy in /root/miniconda3/envs/neucon5/lib/python3.8/site-packages (from torch->torchsparse==2.1.0) (1.13.2)
Requirement already satisfied: networkx in /root/miniconda3/envs/neucon5/lib/python3.8/site-packages (from torch->torchsparse==2.1.0) (3.1)
Requirement already satisfied: jinja2 in /root/miniconda3/envs/neucon5/lib/python3.8/site-packages (from torch->torchsparse==2.1.0) (3.1.4)
Requirement already satisfied: triton==2.0.0 in /root/miniconda3/envs/neucon5/lib/python3.8/site-packages (from torch->torchsparse==2.1.0) (2.0.0)
Requirement already satisfied: cmake in /root/miniconda3/envs/neucon5/lib/python3.8/site-packages (from triton==2.0.0->torch->torchsparse==2.1.0) (3.30.2)
Requirement already satisfied: lit in /root/miniconda3/envs/neucon5/lib/python3.8/site-packages (from triton==2.0.0->torch->torchsparse==2.1.0) (18.1.8)
Requirement already satisfied: requests in /root/miniconda3/envs/neucon5/lib/python3.8/site-packages (from torchvision->torchsparse==2.1.0) (2.32.3)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /root/miniconda3/envs/neucon5/lib/python3.8/site-packages (from torchvision->torchsparse==2.1.0) (10.4.0)
Requirement already satisfied: humanfriendly>=9.1 in /root/miniconda3/envs/neucon5/lib/python3.8/site-packages/humanfriendly-10.0-py3.8.egg (from coloredlogs>=10.0->rootpath->torchsparse==2.1.0) (10.0)
Requirement already satisfied: blessings in /root/miniconda3/envs/neucon5/lib/python3.8/site-packages/blessings-1.7-py3.8.egg (from colour-runner>=0.0.5->rootpath->torchsparse==2.1.0) (1.7)
Requirement already satisfied: orderly-set==5.2.2 in /root/miniconda3/envs/neucon5/lib/python3.8/site-packages/orderly_set-5.2.2-py3.8.egg (from deepdiff>=3.3.0->rootpath->torchsparse==2.1.0) (5.2.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /root/miniconda3/envs/neucon5/lib/python3.8/site-packages (from requests->torchvision->torchsparse==2.1.0) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /root/miniconda3/envs/neucon5/lib/python3.8/site-packages (from requests->torchvision->torchsparse==2.1.0) (3.8)
Requirement already satisfied: urllib3<3,>=1.21.1 in /root/miniconda3/envs/neucon5/lib/python3.8/site-packages (from requests->torchvision->torchsparse==2.1.0) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in /root/miniconda3/envs/neucon5/lib/python3.8/site-packages (from requests->torchvision->torchsparse==2.1.0) (2024.8.30)
Requirement already satisfied: cachetools>=5.4 in /root/miniconda3/envs/neucon5/lib/python3.8/site-packages/cachetools-5.5.0-py3.8.egg (from tox>=3.0.0->rootpath->torchsparse==2.1.0) (5.5.0)
Requirement already satisfied: chardet>=5.2 in /root/miniconda3/envs/neucon5/lib/python3.8/site-packages/chardet-5.2.0-py3.8.egg (from tox>=3.0.0->rootpath->torchsparse==2.1.0) (5.2.0)
Requirement already satisfied: colorama>=0.4.6 in /root/miniconda3/envs/neucon5/lib/python3.8/site-packages/colorama-0.4.6-py3.8.egg (from tox>=3.0.0->rootpath->torchsparse==2.1.0) (0.4.6)
Requirement already satisfied: packaging>=24.1 in /root/miniconda3/envs/neucon5/lib/python3.8/site-packages (from tox>=3.0.0->rootpath->torchsparse==2.1.0) (24.1)
Requirement already satisfied: platformdirs>=4.2.2 in /root/miniconda3/envs/neucon5/lib/python3.8/site-packages (from tox>=3.0.0->rootpath->torchsparse==2.1.0) (4.2.2)
Requirement already satisfied: pluggy>=1.5 in /root/miniconda3/envs/neucon5/lib/python3.8/site-packages/pluggy-1.5.0-py3.8.egg (from tox>=3.0.0->rootpath->torchsparse==2.1.0) (1.5.0)
Requirement already satisfied: pyproject-api>=1.7.1 in /root/miniconda3/envs/neucon5/lib/python3.8/site-packages/pyproject_api-1.7.1-py3.8.egg (from tox>=3.0.0->rootpath->torchsparse==2.1.0) (1.7.1)
Requirement already satisfied: tomli>=2.0.1 in /root/miniconda3/envs/neucon5/lib/python3.8/site-packages/setuptools/_vendor (from tox>=3.0.0->rootpath->torchsparse==2.1.0) (2.0.1)
Requirement already satisfied: virtualenv>=20.26.3 in /root/miniconda3/envs/neucon5/lib/python3.8/site-packages/virtualenv-20.26.3-py3.8.egg (from tox>=3.0.0->rootpath->torchsparse==2.1.0) (20.26.3)
Requirement already satisfied: MarkupSafe>=2.0 in /root/miniconda3/envs/neucon5/lib/python3.8/site-packages (from jinja2->torch->torchsparse==2.1.0) (2.1.5)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /root/miniconda3/envs/neucon5/lib/python3.8/site-packages (from sympy->torch->torchsparse==2.1.0) (1.3.0)
Requirement already satisfied: distlib<1,>=0.3.7 in /root/miniconda3/envs/neucon5/lib/python3.8/site-packages/distlib-0.3.8-py3.8.egg (from virtualenv>=20.26.3->tox>=3.0.0->rootpath->torchsparse==2.1.0) (0.3.8)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.

### Environment

```markdown
- GCC:11.4.0
- NVCC:cuda_11.8.r11.8
- PyTorch:2.0.0+cu118
- PyTorch CUDA:11.8
```

### Full Error Log

<details>
  <summary>Error Log</summary>

  [PUT YOUR ERROR LOG HERE]
</details>

**Comment by zyshan0929** [comment]
I fixed this issue by this:
$ pip install --upgrade git+https://github.com/mit-han-lab/torchsparse.git@v1.4.0

**Comment by liyuan-qiu** [comment]
Thanks ～

Sincerely,

Liyuan Qiu (仇丽媛),




zyshan0929 ***@***.***>于2024年9月24日 周二下午11:11写道：
