### ISSUE TITLE
Unable to install via install script or manual download - wheels down.

### ISSUE THREAD

**Issue by perrineedham** [mit-han-lab/torchsparse#330]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you followed all the steps in the FAQ?

- [X] I have tried the steps in the FAQ.

### Current Behavior

`python3 -c "$(curl -fsSL https://raw.githubusercontent.com/mit-han-lab/torch
sparse/master/install.py)"
Traceback (most recent call last):
  File "<string>", line 40, in <module>
KeyError: 'torch24'`

`http://pypi.hanlab.ai/simple/torchsparse`

> Application Blocked

> Access to the application you were trying to use has been blocked in accordance with company policy. Please contact your system administrator if you believe this is in error.
> 
> User: 76.113.9.191
> 
> Application: web-browsing

I am running with torch 2.4 and cuda 12.4. Can you advise on how to install? 

### Error Line

Downloading seems to work without a problem when using `FORCE_CUDA=1 pip install --no-cache-dir git+https://github.com/mit-han-lab/torchsparse.git` however, I want to install via wheels for easier integration into our codebase. 

### Environment

```markdown
- GCC: 
- NVCC: 12.4
- PyTorch: 2.4
- PyTorch CUDA: 12.4
```

**Comment by tharsosventures** [comment]
Hi @perrineedham, I'm also seeing this issue. I believe it originates from the fact that there is no key for torch 24 (2.4) in the pytorch, cuda version mapping. If you downgrade your version to 2.0, it should install correctly. Alternatively, maybe it's as simple as adding 2.4 to this dictionary.  

From install.py
torch_cuda_mapping = dict(
    [
        ("torch19", ["11.1"]),
        ("torch110", ["11.1", "11.3"]),
        ("torch111", ["11.3", "11.5"]),
        ("torch112", ["11.3", "11.6"]),
        ("torch113", ["11.6", "11.7"]),
        ("torch20", ["11.7", "11.8"]),
    ]
)

**Comment by ollyestn** [comment]
\mit-han-lab\torchsparse>python install.py
Looking in indexes: https://pypi.python.org/simple, http://24.199.104.228/simple
ERROR: Could not find a version that satisfies the requirement torchsparse==2.0.0+torch20cu118 (from versions: none)
ERROR: No matching distribution found for torchsparse==2.0.0+torch20cu118

torchsparse==2.1.0 has the same error.
how to solve this problem?
