### ISSUE TITLE
About the order of coordinates and features after convolution

### ISSUE THREAD

**Issue by MiZhenxing** [mit-han-lab/torchsparse#42]
Hi, thank you for you excellent work. I have found in this [issue](https://github.com/mit-han-lab/torchsparse/issues/14) that Stride=1 version is the submanifold convolution. So in this case the output has the same shape as the input. My questions is whether the order of coordinates and features of the output have the same order as those in the input? If not, is there any way to convert the order of the output into the order of the input? Hope I make myself clear. Thank you!

**Comment by kentangSJTU** [comment]
Hello,

In general if stride = 1, the order will not be changed. Otherwise, the order can be changed because we actually sort points by hash values of coordinates instead of xyz values.

Best,
Haotian

**Comment by MiZhenxing** [comment]
Thank you for your helpful comment!
