### ISSUE TITLE
Comparison to SparseConvNet

### ISSUE THREAD

**Issue by victoryc** [mit-han-lab/torchsparse#43]
From the point of view of 3D semantic labeling and instance segmentation, how does this library compare to SparseConvNet? I understand this library is faster. But, are there any other pros/cons? Is there is implication on performance (i.e., measures such as IOU, mAP etc.)?
Thanks.

**Comment by zhijian-liu** [comment]
This library aims to provide a faithful yet more efficient implementation for the sparse convolution, which is the core building block of many popular 3D neural networks (including SparseConvNet that you mention). It is supposed to provide the same performance as other libraries when provided with the same model architecture. If you are looking for higher performance, you can refer to our SPVNAS (http://spvnas.mit.edu/).
