### ISSUE TITLE
Supporting PointTensor in sparse_collate_fn

### ISSUE THREAD

**Issue by YaraAlnaggar** [mit-han-lab/torchsparse#5]
Hello 
Is there a reason for not supporting PointTensor object types as SparseTensor in sparse_collate_fn. By support I mean adding the batch index to for each point coordinate same as SparseTensor. 

Thanks.

**Comment by kentangSJTU** [comment]
Hello,

Thanks for your interest! We currently support batched PointTensor by converting them from SparseTensor. Here is an [example](https://github.com/mit-han-lab/e3d/blob/0d7d0179d8512fb13d9651dddfb74334218c69b4/spvnas/core/models/semantic_kitti/spvcnn.py#L192). We always want to take advantage of the `sparse_quantize` function to denoise the data first so first building the SparseTensor might be a better idea.


Best,
Haotian

**Comment by YaraAlnaggar** [comment]
Thanks for the clarification and for sharing your work.
