### ISSUE TITLE
GroupNorm

### ISSUE THREAD

**Issue by victoryc** [mit-han-lab/torchsparse#51]
Seems like GroupNorm isn't currently available in the library. Would it be easy to add one? Any guidance on implementing it would be helpful.

**Comment by zhijian-liu** [comment]
You could refer to https://github.com/mit-han-lab/torchsparse/blob/master/torchsparse/nn/modules/norm.py and add a `GroupNorm` module there.

**Comment by zhijian-liu** [comment]
Feel free to submit a PR for this.
