### ISSUE TITLE
3D UNet with TorchSparse

### ISSUE THREAD

**Issue by victoryc** [mit-han-lab/torchsparse#53]
By chance, has anyone implemented 3D UNet with TorchSparse? If so, I would appreciate a link.

The specific issue I am currently pondering about is how to concatenate the features at a level with the up-sampled features from lower level. I looked to see whether there is a built-in function to do that. The functions I saw didn't seem to be right fits.

Things I saw:

- The add function in SparseTensor: This assumes that the coordinates in the two tensors are identical, i.e., the ".C" field is the same in the two tensors. But, this need not be the situation in the UNet case.
- sparse_collate_tensors function in helpers.py : Seems to be for the purpose of creating a tensor where in multiple tensors are added into a batch (?).
Is there a function that would be a better fit?

Thanks.

**Comment by zhijian-liu** [comment]
I'm not sure what kind of U-Net you are looking for. SPVNAS is following a U-Net structure and has the concatenation between features.

**Comment by victoryc** [comment]
Thanks! I just now went to that project. Seems like you may be referring to the code in the following file? I will take a look.
https://github.com/mit-han-lab/spvnas/blob/master/core/models/semantic_kitti/minkunet.py

**Comment by zhijian-liu** [comment]
Exactly. Let me know if you need anything else.

**Comment by HaFred** [comment]
Hi @zhijian-liu , sorry to bring out this issue, but I am just curious is it even possible to do the summation between two `SparseTensor` with different numbers of voxels? Just like the author here mentioned in:
> The add function in SparseTensor: This assumes that the coordinates in the two tensors are identical, i.e., the ".C" field is the same in the two tensors. But, this need not be the situation in the UNet case.

Thanks in advance.

**Comment by HaFred** [comment]
This summation operation is smooth in [MinkEngine](https://nvidia.github.io/MinkowskiEngine/tutorial/sparse_tensor_basic.html#sparse-tensor-arithmetics). I wonder is there any workaround in torchsparse for this?

**Comment by HaFred** [comment]
I came up with this implementation that seems to be functioning, could you @zhijian-liu @kentang-mit kindly check if it is the most efficient way to conduct a `SparseTensor` summation (union) with the current APIs? Thanks a lot.
```python
from torch_scatter import scatter

def sparse_tensor_summation(x0, x1):
    coord_cat = torch.cat((x0.C, x1.C))
    feat_cat = torch.cat((x0.F, x1.F))
    spt_hash = F.sphash(coord_cat)
    spt_hash_unique = torch.unique(spt_hash)
    idx_query = F.sphashquery(spt_hash, spt_hash_unique)
    counts = F.spcount(idx_query.int(), len(spt_hash_unique))

    new_coords = F.spvoxelize(coord_cat.float(), idx_query, counts).int()
    new_feat = scatter(src=feat_cat, index=idx_query, dim=0, reduce='sum')
    out_sparse_tensor = SparseTensor(new_feat, new_coords, x0.s)
    out_sparse_tensor.cmaps.setdefault(out_sparse_tensor.stride, out_sparse_tensor.coords)
    return out_sparse_tensor
```
