### ISSUE TITLE
Submanifold Sparse Convolution

### ISSUE THREAD

**Issue by FrancescoMandru** [mit-han-lab/torchsparse#57]
Hello, I wonder if torchsparse spnn.Conv3d is an implementation of the submanifold sparse convolution (https://arxiv.org/pdf/1706.01307.pdf) or just a sparse convolution. If so can you explain to me the principal difference? Thank you

**Comment by zhijian-liu** [comment]
See https://github.com/mit-han-lab/torchsparse/issues/14.
