### ISSUE TITLE
Can torchsparse process batch-wise point cloud data?

### ISSUE THREAD

**Issue by HilbertXu** [mit-han-lab/torchsparse#60]
Hi,

Thanks for your useful torchsparse. I notices that in tutorials, torchsparse can only be used to process single scene data. If I want to process multiple scene point cloud data with shape [B, N, 4], what should I do? I can't find document about this. 

Sincerely thanks for your reply!

Best regards,

Hilbert Xu

**Comment by OswaldoBornemann** [comment]
@HilbertXu  I have the same question. May I know how you solve it ? Thanks.
