### ISSUE TITLE
Add support for 2D convolution

### ISSUE THREAD

**Issue by FrancescoMandru** [mit-han-lab/torchsparse#61]
Is there any plan to add support for 2d convolutions?

**Comment by zhijian-liu** [comment]
We do not have plans for supporting 2D sparse convolutions in the near future. A quick hack for this might be always setting z to 0 (which might be not optimal in terms of acceleration). I'm wondering what the use case is for using 2D sparse convolutions.

**Comment by FrancescoMandru** [comment]
@zhijian-liu In cases where the image is very sparse and you want to optimize the network, for example the MNIST digits is sparse.

**Comment by zhijian-liu** [comment]
Thanks for the clarification. I think you can try to mimic the 2D convolution with the 3D one. The overhead should not be very large.
