### ISSUE TITLE
datatype cast warning which may cause bugs

### ISSUE THREAD

**Issue by jackmsye** [mit-han-lab/torchsparse#62]
@zhijian-liu 
Hi, firstly thanks for your great work. I found some warnings which may cause bugs.

https://github.com/mit-han-lab/torchsparse/blob/master/torchsparse/src/others/query.cpp#L38 in this line, you cast a long pointer to a ulong pointer. This may cause some overflow when your value in lookup_vals function exceed the numeric maximum of long.

**Comment by zhijian-liu** [comment]
@kentangSJTU, could you please take a look at this? Thanks!

**Comment by kentangSJTU** [comment]
Hi @jackmsye,

Thanks for the question and sorry for the delayed response. Here we assume the values will not exceed the numeric maximum of long (see https://github.com/mit-han-lab/torchsparse/blob/a50506a904f336dfe8f96b3393f7e9ac2b8f1950/torchsparse/src/hash/hash_gpu.cu#L16 for the generation of hash values, where we actually just keep 60 bits). I remember the reason why I use such cast is that I want to use the atomicExch function of CUDA (which does not support signed long at the time I develop the code).

Best,
Haotian

**Comment by jackmsye** [comment]
@kentangSJTU great, thx for your explanation.
