### ISSUE TITLE
Random seed, repeatability

### ISSUE THREAD

**Issue by victoryc** [mit-han-lab/torchsparse#65]
I am noticing that repeated runs of the same code with same data is producing somewhat different results. Is there something we need to do get repeatable pseudo-random behavior with TorchSparse?

I am calling the following at the beginning of my script to ensure repeatability as far as PyTorch is considered. 

```
        torch.manual_seed(manual_seed)
        torch.backends.cudnn.deterministic = True
        torch.backends.cudnn.benchmark = False
```

**Comment by zhijian-liu** [comment]
Yes, it's because the FP atomic addition has nondeterministic behavior...
