### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by digital-idiot** [mit-han-lab/torchsparse#67]
Some functionalities this library provides aren't always intuitive therefore some `docstrings` would be very helpful.

**Comment by zhijian-liu** [comment]
Thanks for your feedback! There are indeed very limited documentations for TorchSparse right now. We designed our API to be as close to PyTorch as possible. However, there is also a few backend APIs that is harder to understand. We will add more documentation in the future (but it will not in our top priority as our focus is more on efficiency). If you find anything in the library that is unclear, please do not hesitate to post them in the issues.

**Comment by digital-idiot** [comment]
Can you explain a bit about these methods (except maybe `conv3d`, this I kind of understood from the use cases in [torch-points3d](https://github.com/nicolas-chaulet/torch-points3d) and [spvnas](https://github.com/mit-han-lab/spvnas)): https://github.com/mit-han-lab/torchsparse/blob/a50506a904f336dfe8f96b3393f7e9ac2b8f1950/torchsparse/nn/modules/conv.py#L10 
 
 I can guess the functionality from their names but I want to be sure. Also can you specify the shape of the input tensor and output tensor for each of these case (where applicable / possible offcourse).

**Comment by CCInc** [comment]
@digital-idiot `torchsparse.nn.modules.conv3d` is a normal sparse convolution. The parameters follow from a [dense pytorch convolution](https://pytorch.org/docs/stable/generated/torch.nn.Conv3d.html). The functional version takes the following inputs:

```
def conv3d(inputs, # SparseTensor for N input points
                   # C = coordinates of shape (N, 4) for C[:,0:3] as quantized coordinates and C[:,3] as batch indices
                   # F = features of shape (N, x) for x>0 features per point
           kernel, # Volumetric kernel of shape (kernel_size**3, in_channels, out_channels)
           kernel_size, # length of kernel along one dimension
           bias=None,	# rest of the args are the same as non-functional
           stride=1,
           dilation=1,
           transpose=False)
```

'ToBEVConvolution', 'ToBEVReduction', 'ToDenseBEVConvolution'  are just object detection helper functions as I understand (https://github.com/mit-han-lab/spvnas/issues/13).

**Comment by digital-idiot** [comment]
Thanks @CCInc. I understood `conv3d` and partly `ToDenseBEVConvolution`. What I don't understand so far are `ToBEVConvolution`, and `ToBEVReduction`. Below is my own implementation of converting voxelized `SparseTensor` to dense 5D tensor. If I understood it correctly, a voxel may contain numerous points, thus an aggregation function or pooling when doing this. I don't see that in any of the  `ToDenseBEVConvolution`, `ToBEVReduction` or `ToBEVConvolution`. That is why I am curious know about these three functions.

```python
import torch_scatter

def voxel_to_grid(x, shape, offset=None, pooling='avg'):

    coords = x.C[:, :-1].cpu().numpy()
    assert coords.shape[-1] == len(shape)
    if offset:
        coords -= offset
    
    flat_indexes = np.ravel_multi_index(
        multi_index=(coords[:, ax] for ax in range(len(shape))),
        dims=shape,
        mode='raise',
        order='C'
    )
    flat_indexes = torch.tensor(
        data=flat_indexes, dtype=torch.long, device=x.F.device
    )
    grid_shape = (*shape, x.F.shape[-1])
    fgrid_shape = (reduce(operator.mul, grid_shape[:-1], 1), grid_shape[-1])
    fgrid = torch.zeros(
        size=fgrid_shape,
        dtype=x.F.dtype,
        device=x.F.device
    )
    if pooling.lower() == 'avg':
        fgrid = torch_scatter.scatter_mean(
            src=x.F,
            index=flat_indexes,
            dim=0,
            out=fgrid
        )
    elif pooling.lower() == 'max':
        fgrid = torch_scatter.scatter_max(
            src=x.F,
            index=flat_indexes,
            dim=0,
            out=fgrid
        )
    elif pooling.lower() == 'min':
        fgrid = torch_scatter.scatter_min(
            src=x.F,
            index=flat_indexes,
            dim=0,
            out=fgrid
        )
    else:
        raise NotImplementedError(
            'Unknown Pooling Operation: {}'.format(pooling)
        )
    grid = torch.reshape(input=fgrid, shape=grid_shape)
    return grid
```

**Comment by digital-idiot** [comment]
The previous implementation was incomplete, it did not consider the batch dimension. Below is the new one. @CCInc , @zhijian-liu can you have a quick look and let me know if the approach is somewhat correct? 

```python
def voxel_to_grid(
    x,
    vol_shape,
    index_offset=None,
    pooling='avg'
):
    """
    Converts SparseTensor with quantized coordinates to dense grid Tensor (5D)
    :param x: SparseTensor with quantized coordinates
    :param vol_shape: Volumetric shape (H, W, Z)
    :param index_offset: Offset of the index (X, Y, Z, B)
    :param pooling: Type of pooling {'avg', 'max', 'min'}
    :return: Tensor with shape (H, W, Z, B, C)
    TODO: Add an option for initializer (such as uniform, normal, xavier etc.)
    """
    # This is just to make use of `numpy.ravel_multi_index` (Yes, I am lazy!)
    coords = x.C.cpu().numpy()
    if index_offset:
        coords -= index_offset
    batch_size = coords[:, -1].max() + 1
    flat_indexes = np.ravel_multi_index(
        multi_index=coords,
        dims=(*vol_shape, batch_size),
        mode='raise',
        order='C'
    )
    # Tensor with raveled index with matching rows size
    flat_indexes = torch.tensor(
        data=flat_indexes, dtype=torch.long, device=x.F.device
    )

    # This is the vol_shape of output tensor (H W Z B C)
    grid_shape = (*vol_shape, batch_size, x.F.shape[-1])

    # Flattened shape (N, C): N = H × W × Z × B
    fgrid_shape = (reduce(operator.mul, grid_shape[:-1], 1), grid_shape[-1])
    fgrid = torch.empty(
        size=fgrid_shape,
        dtype=x.F.dtype,
        device=x.F.device
    )

    # pooling / aggregation to ensure single feature for each voxel
    # Relies on https://pytorch-scatter.readthedocs.io for the pooling ops
    if pooling.lower() == 'avg':
        fgrid = torch_scatter.scatter_mean(
            src=x.F,
            index=flat_indexes,
            dim=0,
            out=fgrid
        )
    elif pooling.lower() == 'max':
        fgrid = torch_scatter.scatter_max(
            src=x.F,
            index=flat_indexes,
            dim=0,
            out=fgrid
        )
    elif pooling.lower() == 'min':
        fgrid = torch_scatter.scatter_min(
            src=x.F,
            index=flat_indexes,
            dim=0,
            out=fgrid
        )
    else:
        raise NotImplementedError(
            'Unknown Pooling Operation: {}'.format(pooling)
        )
    grid = torch.reshape(input=fgrid, shape=grid_shape)
    # TODO: Rearrange the axis here as required
    return grid

```

**Comment by CCInc** [comment]
If you've already voxelized the coords using one of the helper functions like `sparse_quantize`, it should remove the duplicates automatically. `SparseTensor` objects would usually contain unique coord ids. If your goal is just to create a dense representation from sparse coords, then one approach would be to create a `(H,W,D,C)` tensor and assign `C` based on the sparse `X,Y,Z` coords, i.e. 

```
sparse = SparseTensor(feats, coords)
dense = tensor.ones(H,W,D,B,C)
dense[sparse.C] = sparse.F
```

**Comment by digital-idiot** [comment]
> If your goal is just to create a dense representation from sparse coords, then one approach would be to create a `(H,W,D,C)` tensor and assign `C` based on the sparse `X,Y,Z` coords, i.e.
> 
> ```python
> sparse = SparseTensor(feats, coords)
> dense = tensor.zeros(H,W,D,B,C)
> dense[sparse.C] = sparse.F
> ```

@CCInc thanks for clarifying. Yes, `sparse_quantize` is mentioned in the `README` of this repository. But the implementation of the voxelization funtions [initial_voxelize](https://github.com/mit-han-lab/spvnas/blob/f292399ca08fb7decc9e9b718c322000e3e807e3/core/models/utils.py#L15) and [point_to_voxel](https://github.com/mit-han-lab/spvnas/blob/f292399ca08fb7decc9e9b718c322000e3e807e3/core/models/utils.py#L40) from [spvnas](https://github.com/mit-han-lab/spvnas) are seems quite different from `sparse_quantize` here. These two functions relies on `sphash`, `sphashquery`, and `spvoxelize` functions from [torchsparse](https://github.com/mit-han-lab/torchsparse). This is because in the [SPVNAS paper : section 3.3 ](https://arxiv.org/pdf/2007.16100.pdf) they (@zhijian-liu ) specified:

> we propose to use the GPU hash table to accelerate the sparse voxelization and devoxelization. Specifically, we first construct a hash table for all activated points in the sparse voxelized tensor S, which can be completed in O(n) time. After that, we iterate over all points in T, and for each point, we use its voxelized coordinate as the key to query the corresponding index in the sparse voxelized tensor. As the lookup over the hash table requires O(1) time [37], this query step will in total take O(m) time. Therefore, the total time of coordinate indexing will be reduced from O(mn) to O(m+n).

My intention was to use `initial_voxelize` and `point_to_voxel` instead of `sparse_quantize` which seem to be more efficient. In that  respect, I was wondering if

> it should remove the duplicates automatically.

is valid or not.

**Comment by zhijian-liu** [comment]
Sorry for the late reply! These functions deal with the duplicate coordinates using the default behavior of `torch.cuda.float.SparseTensor`, which can be seen from https://pytorch.org/docs/stable/sparse.html:
```
PyTorch sparse COO tensor format permits uncoalesced sparse tensors, where there may be duplicate coordinates in the indices; in this case, the interpretation is that the value at that index is the sum of all duplicate value entries.
```

**Comment by zhijian-liu** [comment]
@CCInc, thank you so much for following up on this.

@digital-idiot, your `voxel_to_grid` implementation looks correct to me.
