### ISSUE TITLE
Trouble with running on CPU

### ISSUE THREAD

**Issue by nicolas-chaulet** [mit-han-lab/torchsparse#7]
Hi,
Awesome library! I am in the process of adding it to [Torch Points3d](https://github.com/nicolas-chaulet/torch-points3d) but I am having troubles getting to run on CPU. For example running the example you provide by forcing the model to be on CPU gives the following:
```
(torch-points3d-AKCjwQtX-py3.7) ChauletN@air4:~/torchsparse/examples$ python example.py 
Starting dummy training...
Traceback (most recent call last):
  File "example.py", line 74, in <module>
    dummy_train(device)
  File "example.py", line 66, in dummy_train
    loss.backward()
  File "/home/ChauletN/.cache/pypoetry/virtualenvs/torch-points3d-AKCjwQtX-py3.7/lib/python3.7/site-packages/torch/tensor.py", line 185, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/ChauletN/.cache/pypoetry/virtualenvs/torch-points3d-AKCjwQtX-py3.7/lib/python3.7/site-packages/torch/autograd/__init__.py", line 127, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError
```
All works great on gpu, any idea what might be wrong?

**Comment by zhijian-liu** [comment]
Thank you so much for your interest in our library and also your efforts to integrate our library into Torch Point3D. Currently, the CPU version still has some bugs, and we are working actively on that. We will keep you informed once that is fixed. Thanks!

**Comment by nicolas-chaulet** [comment]
Ha! I did not realise, thanks for the info. We will integrate it to Torch Points3d as a drop in replacement for sparse convolutions but will keep Minkowski as our main backend for now. (Until torch sparse catches up!)
By the way, after some benchmarking I can definitely confirm that it is faster than Minkowski 0.5. Great work!

**Comment by nicolas-chaulet** [comment]
> to integrate our library into Torch Point3D
No worries! It is actually integrated now, and we allow swapping weights between `Minkowski` and `torchsparse` which solves this issue for now because `Minkowski` supports CPU. So one can train using `torchsparse` and deploy a `Minkowski` model with those weights.

**Comment by zhijian-liu** [comment]
I think the CPU inference issue has been resolved for a while. Feel free to reopen the issue if there is any other issue.

**Comment by FrancescoMandru** [comment]
I have similar issues and I opened a new one
