### ISSUE TITLE
Mixed precision or FP16 support!

### ISSUE THREAD

**Issue by YoushaaMurhij** [mit-han-lab/torchsparse#71]
Great Work! Do you have a plan to add support for FP16 mode or conversion to TensorRT to improve the performance?
It will be great if we can convert the SparseTensor to a lower precision like Pytorch tensors.

**Comment by owoshch** [comment]
Hi @zhijian-liu!
Thank you for your work! 
Could you share your opinion on the porting SPVNAS models (or any other models that use torchspase) to TensortRT (fp16, int8 or any other scheme) in order to increase the running time?

**Comment by zhijian-liu** [comment]
Porting TorchSparse models to TensorRT is very hard as the sparse convolution is not natively supported by TensorRT. However, we are actively working on our own FP16/INT8 inference support. Stay tuned!

**Comment by sandeepnmenon** [comment]
Is there a way to port it to TensorRT? Even if it is hard :) 
I would like some direction to explore and see how feasible it is

**Comment by zhijian-liu** [comment]
It's technically doable, but unfortunately we don't have the bandwidth to work on this recently. The most viable approach would be to register our sparse modules as plugins in ONNX and TensorRT so that they can recognize them correctly.
