### ISSUE TITLE
CUDA Half Compilation Error

### ISSUE THREAD

**Issue by CCInc** [mit-han-lab/torchsparse#72]
On some environments, I'm getting the following error from `pip install git+https://github.com/mit-han-lab/torchsparse.git`:

>   /usr/local/cuda-10.2/bin/nvcc -I/home/x/miniconda3/envs/tp3d_pdal/lib/python3.8/site-packages/torch/include -I/home/x/miniconda3/envs/tp3d_pdal/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/x/miniconda3/envs/tp3d_pdal/lib/python3.8/site-packages/torch/include/TH -I/home/x/miniconda3/envs/tp3d_pdal/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-10.2/include -I/home/x/miniconda3/envs/tp3d_pdal/include/python3.8 -c -c /tmp/pip-req-build-n5yhswsl/torchsparse/src/others/insertion_gpu.cu -o /tmp/pip-req-build-n5yhswsl/build/temp.linux-x86_64-3.8/torchsparse/src/others/insertion_gpu.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=torchsparse_backend -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_52,code=sm_52 -std=c++14
>   /home/x/miniconda3/envs/tp3d_pdal/lib/python3.8/site-packages/torch/include/ATen/core/boxing/impl/boxing.h(100): warning: integer conversion resulted in a change of sign
>   
>   /home/x/miniconda3/envs/tp3d_pdal/lib/python3.8/site-packages/torch/include/ATen/core/op_registration/op_whitelist.h(39): warning: integer conversion resulted in a change of sign
>   
>   /tmp/pip-req-build-n5yhswsl/torchsparse/src/others/../common/gpu.cuh(109): error: no instance of overloaded function "atomicAdd" matches the argument list
>               argument types are: (__half *, c10::Half)

Failing on the following env:

> $ g++ --version
> g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
> Copyright (C) 2017 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> 
> $ nvcc --version
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2019 NVIDIA Corporation
> Built on Wed_Oct_23_19:24:38_PDT_2019
> Cuda compilation tools, release 10.2, V10.2.89
> $ python -c "import torch; print(torch.__version__)"
> 1.7.0
> 

But compiles fine on:

> 
> $ g++ --version
> g++ (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
> Copyright (C) 2015 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> 
> $ nvcc --version
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2019 NVIDIA Corporation
> Built on Wed_Oct_23_19:24:38_PDT_2019
> Cuda compilation tools, release 10.2, V10.2.89
> $ python -c "import torch; print(torch.__version__)"
> 1.7.0

@zhijian-liu could you let me know the environment you were able to compile on?

**Comment by zhijian-liu** [comment]
The environment I was using is as follows:
```
$ g++ --version
g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89

$ python -c "import torch; print(torch.__version__)"
1.8.1
```

Thanks for investigating this issue!

**Comment by CCInc** [comment]
It looks like this is an issue with CUDA architecture. I can reproduce it by setting `TORCH_CUDA_ARCH_LIST="6.0"` but it works fine with `TORCH_CUDA_ARCH_LIST="6.0"`, I think older architectures don't support the half precision atomicAdd (similar to double). I'll try to find an implementation
