### ISSUE TITLE
CUDA Compliation error: "error: no instance of overloaded function "atomicAdd" matches the argument list"

### ISSUE THREAD

**Issue by JBKnights** [mit-han-lab/torchsparse#73]
Hi,

When compiling torchsparse 1.3 I ran into the following compile error:

> /tmp/kni101.51806/pip-req-build-61xiw2ee/torchsparse/src/others/../common/gpu.cuh(109): error: no instance of overloaded function "atomicAdd" matches the argument list
              argument types are: (__half *, c10::Half)

In an environment running torch=1.8.1, cuda=10.2, gcc=7.3.0.  However, I'm still able to compile torchsparse 10.2 perfectly well - do you have any idea what could be causing this?

**Comment by CCInc** [comment]
Hi! I submitted a PR to fix the issue. @JBKnights please try it out and let me know if it works for you. Thanks!
