### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by ezgicakirofficial** [mit-han-lab/torchsparse#78]
Hello,
I try to install torchsparse to a server.
I write this command: 
`> pip3 install --upgrade git+https://github.com/mit-han-lab/torchsparse.git 1>/dev/null`

At the end of veeery long error message, this is written:
`error: command '/usr/bin/nvcc' failed with exit status 1`

gcc version is 7.4.0, nvcc version is 9.1, CUDA version is 10.2. 
How can I solve the problem? Thanks in advance.

**Comment by kentangSJTU** [comment]
It looks like the nvcc version does not match with the CUDA version. I believe we have to fix this before moving on.

**Comment by ezgicakirofficial** [comment]
Hi,
I thought the same first. After I read this answer (https://stackoverflow.com/a/53504578/10614701) on stackoverflow, I thought maybe it is not necessary. Yet, I guess for this project, versions should match. Thanks for answer.

**Comment by kentangSJTU** [comment]
You're welcome. Feel free to comment again if fixing the version cannot solve your problem.

**Comment by ezgicakirofficial** [comment]
Hello, 
The problem has solved after nvcc and cudo toolkit versions are same. 
Thanks again.
