### ISSUE TITLE
installation problem, g++ error

### ISSUE THREAD

**Issue by dyy0205** [mit-han-lab/torchsparse#87]
hi, how can i fix this installation error?
<img width="1861" alt="截屏2021-06-28下午2 20 41" src="https://user-images.githubusercontent.com/49671641/123590279-05546400-d81d-11eb-80dd-f5c5e1ab4f27.png">

my torch and cuda version as follows:
<img width="1097" alt="截屏2021-06-28下午2 29 29" src="https://user-images.githubusercontent.com/49671641/123590459-4187c480-d81d-11eb-8ea8-0884a5d9720a.png">

and i have already installed sparsehash.

**Comment by dyy0205** [comment]
g++ (GCC) 5.4.0

**Comment by CCInc** [comment]
Did you see the error message posted in your log?

**Comment by dyy0205** [comment]
> Did you see the error message posted in your log?

thanks for your reply!it seems not compile successfully, how can i solve this problem?

**Comment by zhijian-liu** [comment]
It's because your default C++ compiler is `c++` rather than `g++`. You need to set the environment variable `CXX` correctly.
