### ISSUE TITLE
The importance of removing duplicates

### ISSUE THREAD

**Issue by LordLiang** [mit-han-lab/torchsparse#90]
If I just voxelize x, y, z coordinates but not remove duplicates, what will happen? 
I find that when duplicates are not removed, the network also works. I am confused with this. Will the result be wrong?
Can you tell me about some details?

**Comment by zhijian-liu** [comment]
I don't understand the motivation behind keeping duplicates as they are referring to the same voxel grid. If you do not remove duplicates, the same convolution kernel might be applied to the same voxel grid multiple times, which might not lead to a lower performance but is not theoretically correct.
