### ISSUE TITLE
Conda Build

### ISSUE THREAD

**Issue by CCInc** [mit-han-lab/torchsparse#93]
@zhijian-liu @kentangSJTU How would you feel about me adding a conda build? I think it would cut down on some build issues and make it easier for people.

**Comment by zhijian-liu** [comment]
Sounds great! Actually, I found a conda package for TorchSparse before: https://anaconda.org/conda-forge/torchsparse. It would be great if you could take a look at it to see whether it works or not. Thanks!

**Comment by CCInc** [comment]
That's interesting, here's where it came from: https://github.com/conda-forge/staged-recipes/pull/15095

It looks like it's CPU only builds at the moment. I will reach out to the maintainer and see if we can update it to GPU. A bunch of other libraries (torch-points-kernels, pytorch-sparse/scatter/cluster) just got support for conda build as well across multiple CUDA/torch versions, but those are all manually triggered workflows, not sure how that integrates with conda-forge.

**Comment by zhijian-liu** [comment]
Thanks for taking the initiative!
