### ISSUE TITLE
Segmentation fault on Conv3d

### ISSUE THREAD

**Issue by digital-idiot** [mit-han-lab/torchsparse#98]
Below is a demo code snippet resulting into `Segmentation fault`:

```python
In [1]: import torch
   ...: from torchsparse import nn as spnn
   ...: from torchsparse.tensor import SparseTensor
   ...: 
   ...: c = 256 * torch.rand(512, 3, device='cuda', dtype=torch.float32)
   ...: c = torch.cat((c, torch.ones(512, 1, device='cuda', dtype=torch.float32)), dim=1)
   ...: c = c.to(dtype=torch.int32, device='cuda')
   ...: f = torch.randn(512, 2, device='cuda', dtype=torch.float32)
   ...: 
   ...: pt1 = SparseTensor(f, c)
   ...: c3 = spnn.Conv3d(2, 5, kernel_size=3)
   ...: pt2 = c3(pt1)
   ...: 
Segmentation fault (core dumped)

```

* **NOTE:** The following seemed incorrect as it leads to `RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking arugment for argument mat2 in method wrapper_mm_out_out)`:
https://github.com/mit-han-lab/torchsparse/blob/038e6c22a177415da9bf3c907e26d3815f5c66f9/torchsparse/nn/functional/conv.py#L44-L46

So, I changed it to:
```python
if input.device.type == 'cuda':
    torchsparse.backend.convolution_forward_cuda(
        input, output, weight, nbmaps, nbsizes.cuda(), transposed)
```
But it leads to `segmentation fault` as mentioned earlier.

---

* `torchsparse` version: `v1.4.0`
* `torch` version: `1.9.0` (`cuda`)
* `python` version: `3.9.6`
* `cuda` version: `11.1`

**Comment by CCInc** [comment]
Hi @digital-idiot ,

This is a result of `weight` being on the wrong device, not `nbsizes`. `weight` (aka kernel) is a parameter of the Conv3d model. 

For `nn.modules` you still need to specify the correct device, which will change the device of its parameters. So, try this:

`c3 = spnn.Conv3d(2, 5, kernel_size=3).cuda()`

You can see we do the same thing here:

https://github.com/mit-han-lab/torchsparse/blob/038e6c22a177415da9bf3c907e26d3815f5c66f9/examples/example.py#L62-L76

**Comment by digital-idiot** [comment]
> Hi @digital-idiot ,
> 
> This is a result of `weight` being on the wrong device, not `nbsizes`. `weight` (aka kernel) is a parameter of the Conv3d model.
> 
> For `nn.modules` you still need to specify the correct device, which will change the device of its parameters. So, try this:
> 
> `c3 = spnn.Conv3d(2, 5, kernel_size=3).cuda()`
> 
> You can see we do the same thing here:
> 
> https://github.com/mit-han-lab/torchsparse/blob/038e6c22a177415da9bf3c907e26d3815f5c66f9/examples/example.py#L62-L76

Thanks. A silly mistake from my side.
