### ISSUE TITLE
Specify output coordinates for sparse 3D convolution

### ISSUE THREAD

**Issue by lkskstlr** [mit-han-lab/torchsparse#99]
Thank you very much for open-sourcing this code, the performance seems promising in comparison to MinkowskiEngine.

The MinkowskiEngine offers the possibility to evaluate the 3D convolution for different coordinates than the ones used for the input (cf. https://nvidia.github.io/MinkowskiEngine/convolution.html#MinkowskiEngine.MinkowskiConvolution.forward). I couldn't find the equivalent for torchsparse, did I miss it?

Do you plan to support this functionality or could you maybe point me towards how I could quickly "hack it in"?

Thanks again for your work!
Best
Lukas

**Comment by zhijian-liu** [comment]
It's not currently supported in TorchSparse. You should be able to support this by switching `coords` at https://github.com/mit-han-lab/torchsparse/blob/master/torchsparse/nn/functional/conv.py#L117 with the desired output coordinates.

**Comment by lkskstlr** [comment]
Hi @zhijian-liu,

thanks for the hint! Will close the issue for now and keep my fingers crossed for official support.

Best
Lukas
